'use client'

import { Button } from '@/components/ui/button'
import { ContributeToBlueprintButton } from './contribute-to-blueprint-button'

export function HeroSection() {
  return (
    <section className="container mx-auto text-center pt-32 px-6">
      <h1 className="text-5xl md:text-6xl font-bold text-white mb-8">
        A Blueprint for a <br />
        <span className="text-color-gradient-rainbow-accent">
          World Without Disease
        </span>
      </h1>

      <p className="max-w-3xl mx-auto text-neutral-400 mb-12 text-lg leading-relaxed">
        CureDAO is on a mission to unite collective intelligence in creating a Blueprint for a World Without Disease.
        This vision is rooted in three transformative pillars:
      </p>

      <div className="grid md:grid-cols-3 gap-6 max-w-4xl mx-auto mb-12">
        <div className="bg-[#1d1a27] rounded-xl p-6 border border-white/10">
          <h3 className="text-xl font-bold text-white mb-2">Decentralized FDA</h3>
          <p className="text-neutral-400">
            Slash clinical trial costs by 95%, reducing them from $56 million to $2 million by leveraging decentralized, automated trial platforms.
          </p>
        </div>

        <div className="bg-[#1d1a27] rounded-xl p-6 border border-white/10">
          <h3 className="text-xl font-bold text-white mb-2">Patient Rights</h3>
          <p className="text-neutral-400">
            Empower individuals with effortless access to participate in trials for the most promising experimental treatments.
          </p>
        </div>

        <div className="bg-[#1d1a27] rounded-xl p-6 border border-white/10">
          <h3 className="text-xl font-bold text-white mb-2">Fixing Incentives</h3>
          <p className="text-neutral-400">
            Make curing diseases more profitable than managing them by rewarding manufacturers with 50% of the health savings generated by new cures.
          </p>
        </div>
      </div>

      <div className="flex gap-4 justify-center">
        <Button
          className="relative px-8 py-3 text-lg text-white border-transparent bg-transparent hover:bg-transparent group"
        >
          <span className="relative z-10">Join Us</span>
          <div className="absolute inset-0 rounded-full bg-gradient-to-r from-[#ff4895] via-[#00ffcc] to-[#ff8866] opacity-70 group-hover:opacity-100 transition-opacity"></div>
          <div className="absolute inset-[1px] rounded-full bg-[#13111a] z-0"></div>
        </Button>
        <ContributeToBlueprintButton />
      </div>
    </section>
  )
}

