<?php
/*
*  GNU General Public License v3.0
*  Contributors: ADD YOUR NAME HERE, Mike P. Sinn
 */

namespace App\Files;
use Spatie\MediaLibrary\MediaCollections\Exceptions\MimeTypeNotAllowed;
class MimeContentTypeHelper {
	public const EXTENSION_TO_TYPE_MAP = [
		'ai' => 'application/postscript',
		'aif' => 'audio/x-aiff',
		'aifc' => 'audio/x-aiff',
		'aiff' => 'audio/x-aiff',
		'asc' => 'text/plain',
		'atom' => 'application/atom+xml',
		'au' => 'audio/basic',
		'avi' => 'video/x-msvideo',
		'bcpio' => 'application/x-bcpio',
		'bin' => 'application/octet-stream',
		'bmp' => 'image/bmp',
		'cdf' => 'application/x-netcdf',
		'cgm' => 'image/cgm',
		'class' => 'application/octet-stream',
		'cpio' => 'application/x-cpio',
		'cpt' => 'application/mac-compactpro',
		'csh' => 'application/x-csh',
		'css' => 'text/css',
		'csv' => 'text/csv',
		'dcr' => 'application/x-director',
		'dir' => 'application/x-director',
		'djv' => 'image/vnd.djvu',
		'djvu' => 'image/vnd.djvu',
		'dll' => 'application/octet-stream',
		'dmg' => 'application/octet-stream',
		'dms' => 'application/octet-stream',
		'doc' => 'application/msword',
		'dtd' => 'application/xml-dtd',
		'dvi' => 'application/x-dvi',
		'dxr' => 'application/x-director',
		'eps' => 'application/postscript',
		'etx' => 'text/x-setext',
		'exe' => 'application/octet-stream',
		'ez' => 'application/andrew-inset',
		'gif' => 'image/gif',
		'gram' => 'application/srgs',
		'grxml' => 'application/srgs+xml',
		'gtar' => 'application/x-gtar',
		'hdf' => 'application/x-hdf',
		'hqx' => 'application/mac-binhex40',
		'htm' => self::HTML,
		'html' => self::HTML,
		'ice' => 'x-conference/x-cooltalk',
		'ico' => 'image/x-icon',
		'ics' => 'text/calendar',
		'ief' => 'image/ief',
		'ifb' => 'text/calendar',
		'iges' => 'model/iges',
		'igs' => 'model/iges',
		'jpe' => self::JPG,
		'jpeg' => self::JPG,
		'jpg' => self::JPG,
		'js' => 'application/x-javascript',
		'json' => self::JSON,
		'kar' => 'audio/midi',
		'latex' => 'application/x-latex',
		'lha' => 'application/octet-stream',
		'lzh' => 'application/octet-stream',
		'm3u' => 'audio/x-mpegurl',
		'man' => 'application/x-troff-man',
		'map' => 'application/octet-stream',
		'mathml' => 'application/mathml+xml',
		'me' => 'application/x-troff-me',
		'mesh' => 'model/mesh',
		'mid' => 'audio/midi',
		'midi' => 'audio/midi',
		'mif' => 'application/vnd.mif',
		'mov' => 'video/quicktime',
		'movie' => 'video/x-sgi-movie',
		'mp2' => 'audio/mpeg',
		'mp3' => 'audio/mpeg',
		'mpe' => 'video/mpeg',
		'mpeg' => 'video/mpeg',
		'mpg' => 'video/mpeg',
		'mpga' => 'audio/mpeg',
		'ms' => 'application/x-troff-ms',
		'msh' => 'model/mesh',
		'mxu' => 'video/vnd.mpegurl',
		'nc' => 'application/x-netcdf',
		'oda' => 'application/oda',
		'ogg' => 'application/ogg',
		'pbm' => 'image/x-portable-bitmap',
		'pdb' => 'chemical/x-pdb',
		'pdf' => 'application/pdf',
		'pgm' => 'image/x-portable-graymap',
		'pgn' => 'application/x-chess-pgn',
		'png' => 'image/png',
		'pnm' => 'image/x-portable-anymap',
		'ppm' => 'image/x-portable-pixmap',
		'ppt' => 'application/vnd.ms-powerpoint',
		'ps' => 'application/postscript',
		'qt' => 'video/quicktime',
		'ra' => 'audio/x-pn-realaudio',
		'ram' => 'audio/x-pn-realaudio',
		'ras' => 'image/x-cmu-raster',
		'rdf' => 'application/rdf+xml',
		'rgb' => 'image/x-rgb',
		'rm' => 'application/vnd.rn-realmedia',
		'roff' => 'application/x-troff',
		'rss' => 'application/rss+xml',
		'rtf' => 'text/rtf',
		'rtx' => 'text/richtext',
		'sgm' => 'text/sgml',
		'sgml' => 'text/sgml',
		'sh' => 'application/x-sh',
		'shar' => 'application/x-shar',
		'silo' => 'model/mesh',
		'sit' => 'application/x-stuffit',
		'skd' => 'application/x-koan',
		'skm' => 'application/x-koan',
		'skp' => 'application/x-koan',
		'skt' => 'application/x-koan',
		'smi' => 'application/smil',
		'smil' => 'application/smil',
		'snd' => 'audio/basic',
		'so' => 'application/octet-stream',
		'spl' => 'application/x-futuresplash',
		'src' => 'application/x-wais-source',
		'sv4cpio' => 'application/x-sv4cpio',
		'sv4crc' => 'application/x-sv4crc',
		'svg' => 'image/svg+xml',
		'svgz' => 'image/svg+xml',
		'swf' => 'application/x-shockwave-flash',
		't' => 'application/x-troff',
		'tar' => 'application/x-tar',
		'tcl' => 'application/x-tcl',
		'tex' => 'application/x-tex',
		'texi' => 'application/x-texinfo',
		'texinfo' => 'application/x-texinfo',
		'tif' => 'image/tiff',
		'tiff' => 'image/tiff',
		'tr' => 'application/x-troff',
		'tsv' => 'text/tab-separated-values',
		'txt' => 'text/plain',
		'ustar' => 'application/x-ustar',
		'vcd' => 'application/x-cdlink',
		'vrml' => 'model/vrml',
		'vxml' => 'application/voicexml+xml',
		'wav' => 'audio/x-wav',
		'wbmp' => 'image/vnd.wap.wbmp',
		'wbxml' => 'application/vnd.wap.wbxml',
		'wml' => 'text/vnd.wap.wml',
		'wmlc' => 'application/vnd.wap.wmlc',
		'wmls' => 'text/vnd.wap.wmlscript',
		'wmlsc' => 'application/vnd.wap.wmlscriptc',
		'wrl' => 'model/vrml',
		'xbm' => 'image/x-xbitmap',
		'xht' => 'application/xhtml+xml',
		'xhtml' => 'application/xhtml+xml',
		'xls' => 'application/vnd.ms-excel',
		'xml' => 'application/xml',
		'xpm' => 'image/x-xpixmap',
		'xsl' => 'application/xml',
		'xslt' => 'application/xslt+xml',
		'xul' => 'application/vnd.mozilla.xul+xml',
		'xwd' => 'image/x-xwindowdump',
		'xyz' => 'chemical/x-xyz',
		'zip' => 'application/zip',
		'eot' => 'application/vnd.ms-fontobject',
		'ttf' => 'application/octet-stream',
		'woff' => 'font/woff',
		'woff2' => 'font/woff2',
		'md' => 'text/markdown',
		'enc' => 'application/octet-stream',
	];
	public const HTML = 'text/html';
	public const JPG = 'image/jpeg';
	const JSON = 'application/json';
	/**
	 * @param string $fileName
	 * @param string|null $fallback
	 * @return string
	 * @throws MimeTypeNotAllowed
	 */
	public static function guessMimeContentTypeBasedOnFileName(string $fileName, string $fallback = null): string{
		$extension = FileHelper::getExtension($fileName);
		$extension = strtolower($extension);
		if(isset(self::EXTENSION_TO_TYPE_MAP[$extension])){
			return self::EXTENSION_TO_TYPE_MAP[$extension];
		}
		if($fallback){
			return $fallback;
		}
		throw new MimeTypeNotAllowed("Mime type not found for extension $extension in filename $fileName");
	}
	/**
	 * Maps a file extensions to a mimetype.
	 * @param string $filename
	 * @return string|null
	 * @link http://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x/conf/mime.types
	 */
	public static function mimetype_from_extension(string $filename): ?string{
		$extension = FileHelper::getExtension($filename);
		static $mimetypes = [
			'3gp' => 'video/3gpp',
			'7z' => 'application/x-7z-compressed',
			'aac' => 'audio/x-aac',
			'ai' => 'application/postscript',
			'aif' => 'audio/x-aiff',
			'asc' => 'text/plain',
			'asf' => 'video/x-ms-asf',
			'atom' => 'application/atom+xml',
			'avi' => 'video/x-msvideo',
			'bmp' => 'image/bmp',
			'bz2' => 'application/x-bzip2',
			'cer' => 'application/pkix-cert',
			'crl' => 'application/pkix-crl',
			'crt' => 'application/x-x509-ca-cert',
			'css' => 'text/css',
			'csv' => 'text/csv',
			'cu' => 'application/cu-seeme',
			'deb' => 'application/x-debian-package',
			'doc' => 'application/msword',
			'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
			'dvi' => 'application/x-dvi',
			'eot' => 'application/vnd.ms-fontobject',
			'eps' => 'application/postscript',
			'epub' => 'application/epub+zip',
			'etx' => 'text/x-setext',
			'flac' => 'audio/flac',
			'flv' => 'video/x-flv',
			'gif' => 'image/gif',
			'gz' => 'application/gzip',
			'htm' => 'text/html',
			'html' => 'text/html',
			'ico' => 'image/x-icon',
			'ics' => 'text/calendar',
			'ini' => 'text/plain',
			'iso' => 'application/x-iso9660-image',
			'jar' => 'application/java-archive',
			'jpe' => 'image/jpeg',
			'jpeg' => 'image/jpeg',
			'jpg' => 'image/jpeg',
			'js' => 'text/javascript',
			'json' => 'application/json',
			'latex' => 'application/x-latex',
			'log' => 'text/plain',
			'm4a' => 'audio/mp4',
			'm4v' => 'video/mp4',
			'mid' => 'audio/midi',
			'midi' => 'audio/midi',
			'mov' => 'video/quicktime',
			'mkv' => 'video/x-matroska',
			'mp3' => 'audio/mpeg',
			'mp4' => 'video/mp4',
			'mp4a' => 'audio/mp4',
			'mp4v' => 'video/mp4',
			'mpe' => 'video/mpeg',
			'mpeg' => 'video/mpeg',
			'mpg' => 'video/mpeg',
			'mpg4' => 'video/mp4',
			'oga' => 'audio/ogg',
			'ogg' => 'audio/ogg',
			'ogv' => 'video/ogg',
			'ogx' => 'application/ogg',
			'pbm' => 'image/x-portable-bitmap',
			'pdf' => 'application/pdf',
			'pgm' => 'image/x-portable-graymap',
			'png' => 'image/png',
			'pnm' => 'image/x-portable-anymap',
			'ppm' => 'image/x-portable-pixmap',
			'ppt' => 'application/vnd.ms-powerpoint',
			'pptx' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
			'ps' => 'application/postscript',
			'qt' => 'video/quicktime',
			'rar' => 'application/x-rar-compressed',
			'ras' => 'image/x-cmu-raster',
			'rss' => 'application/rss+xml',
			'rtf' => 'application/rtf',
			'sgm' => 'text/sgml',
			'sgml' => 'text/sgml',
			'svg' => 'image/svg+xml',
			'swf' => 'application/x-shockwave-flash',
			'tar' => 'application/x-tar',
			'tif' => 'image/tiff',
			'tiff' => 'image/tiff',
			'torrent' => 'application/x-bittorrent',
			'ttf' => 'application/x-font-ttf',
			'txt' => 'text/plain',
			'wav' => 'audio/x-wav',
			'webm' => 'video/webm',
			'wma' => 'audio/x-ms-wma',
			'wmv' => 'video/x-ms-wmv',
			'woff' => 'application/x-font-woff',
			'wsdl' => 'application/wsdl+xml',
			'xbm' => 'image/x-xbitmap',
			'xls' => 'application/vnd.ms-excel',
			'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
			'xml' => 'application/xml',
			'xpm' => 'image/x-xpixmap',
			'xwd' => 'image/x-xwindowdump',
			'yaml' => 'text/yaml',
			'yml' => 'text/yaml',
			'zip' => 'application/zip',
		];
		$extension = strtolower($extension);
		return $mimetypes[$extension] ?? null;
	}
}
