<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TrackingRemindersTableSeeder extends AbstractSeeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tracking_reminders')->delete();
        
        \DB::table('tracking_reminders')->insert(array (
            0 => 
            array (
                'id' => '1',
                'user_id' => '1',
                'client_id' => 'system',
                'variable_id' => '1398',
                'default_value' => NULL,
                'reminder_start_time' => '20:00:00',
                'reminder_end_time' => NULL,
                'reminder_sound' => NULL,
                'reminder_frequency' => '86400',
                'pop_up' => NULL,
                'sms' => NULL,
                'email' => NULL,
                'notification_bar' => NULL,
                'last_tracked' => NULL,
                'created_at' => '2022-10-02 20:20:46',
                'updated_at' => '2022-10-02 20:20:46',
                'start_tracking_date' => NULL,
                'stop_tracking_date' => NULL,
                'instructions' => NULL,
                'deleted_at' => NULL,
                'image_url' => NULL,
                'user_variable_id' => '23',
                'latest_tracking_reminder_notification_notify_at' => '2022-10-02 01:00:00',
                'number_of_tracking_reminder_notifications' => NULL,
            ),
            1 => 
            array (
                'id' => '2',
                'user_id' => '2',
                'client_id' => 'system',
                'variable_id' => '1398',
                'default_value' => NULL,
                'reminder_start_time' => '20:00:00',
                'reminder_end_time' => NULL,
                'reminder_sound' => NULL,
                'reminder_frequency' => '86400',
                'pop_up' => NULL,
                'sms' => NULL,
                'email' => NULL,
                'notification_bar' => NULL,
                'last_tracked' => NULL,
                'created_at' => '2022-10-02 20:20:46',
                'updated_at' => '2022-10-02 20:20:46',
                'start_tracking_date' => NULL,
                'stop_tracking_date' => NULL,
                'instructions' => NULL,
                'deleted_at' => NULL,
                'image_url' => NULL,
                'user_variable_id' => '25',
                'latest_tracking_reminder_notification_notify_at' => '2022-10-02 01:00:00',
                'number_of_tracking_reminder_notifications' => NULL,
            ),
            2 => 
            array (
                'id' => '3',
                'user_id' => '4',
                'client_id' => 'system',
                'variable_id' => '1398',
                'default_value' => NULL,
                'reminder_start_time' => '20:00:00',
                'reminder_end_time' => NULL,
                'reminder_sound' => NULL,
                'reminder_frequency' => '86400',
                'pop_up' => NULL,
                'sms' => NULL,
                'email' => NULL,
                'notification_bar' => NULL,
                'last_tracked' => NULL,
                'created_at' => '2022-10-02 20:20:47',
                'updated_at' => '2022-10-02 20:20:47',
                'start_tracking_date' => NULL,
                'stop_tracking_date' => NULL,
                'instructions' => NULL,
                'deleted_at' => NULL,
                'image_url' => NULL,
                'user_variable_id' => '27',
                'latest_tracking_reminder_notification_notify_at' => '2022-10-02 01:00:00',
                'number_of_tracking_reminder_notifications' => NULL,
            ),
            3 => 
            array (
                'id' => '4',
                'user_id' => '5',
                'client_id' => 'system',
                'variable_id' => '1398',
                'default_value' => NULL,
                'reminder_start_time' => '20:00:00',
                'reminder_end_time' => NULL,
                'reminder_sound' => NULL,
                'reminder_frequency' => '86400',
                'pop_up' => NULL,
                'sms' => NULL,
                'email' => NULL,
                'notification_bar' => NULL,
                'last_tracked' => NULL,
                'created_at' => '2022-10-02 20:20:48',
                'updated_at' => '2022-10-02 20:20:48',
                'start_tracking_date' => NULL,
                'stop_tracking_date' => NULL,
                'instructions' => NULL,
                'deleted_at' => NULL,
                'image_url' => NULL,
                'user_variable_id' => '28',
                'latest_tracking_reminder_notification_notify_at' => '2022-10-02 01:00:00',
                'number_of_tracking_reminder_notifications' => NULL,
            ),
            4 => 
            array (
                'id' => '5',
                'user_id' => '8',
                'client_id' => 'system',
                'variable_id' => '1398',
                'default_value' => NULL,
                'reminder_start_time' => '20:00:00',
                'reminder_end_time' => NULL,
                'reminder_sound' => NULL,
                'reminder_frequency' => '86400',
                'pop_up' => NULL,
                'sms' => NULL,
                'email' => NULL,
                'notification_bar' => NULL,
                'last_tracked' => NULL,
                'created_at' => '2022-10-02 20:20:50',
                'updated_at' => '2022-10-02 20:20:50',
                'start_tracking_date' => NULL,
                'stop_tracking_date' => NULL,
                'instructions' => NULL,
                'deleted_at' => NULL,
                'image_url' => NULL,
                'user_variable_id' => '29',
                'latest_tracking_reminder_notification_notify_at' => '2022-10-02 20:00:00',
                'number_of_tracking_reminder_notifications' => NULL,
            ),
            5 => 
            array (
                'id' => '6',
                'user_id' => '230',
                'client_id' => 'system',
                'variable_id' => '1398',
                'default_value' => NULL,
                'reminder_start_time' => '20:00:00',
                'reminder_end_time' => NULL,
                'reminder_sound' => NULL,
                'reminder_frequency' => '86400',
                'pop_up' => NULL,
                'sms' => NULL,
                'email' => NULL,
                'notification_bar' => NULL,
                'last_tracked' => NULL,
                'created_at' => '2022-10-02 20:20:51',
                'updated_at' => '2022-10-02 20:20:51',
                'start_tracking_date' => NULL,
                'stop_tracking_date' => NULL,
                'instructions' => NULL,
                'deleted_at' => NULL,
                'image_url' => NULL,
                'user_variable_id' => '30',
                'latest_tracking_reminder_notification_notify_at' => '2022-10-02 20:00:00',
                'number_of_tracking_reminder_notifications' => NULL,
            ),
            6 => 
            array (
                'id' => '7',
                'user_id' => '11000',
                'client_id' => 'system',
                'variable_id' => '1398',
                'default_value' => NULL,
                'reminder_start_time' => '20:00:00',
                'reminder_end_time' => NULL,
                'reminder_sound' => NULL,
                'reminder_frequency' => '86400',
                'pop_up' => NULL,
                'sms' => NULL,
                'email' => NULL,
                'notification_bar' => NULL,
                'last_tracked' => NULL,
                'created_at' => '2022-10-02 20:20:52',
                'updated_at' => '2022-10-02 20:20:52',
                'start_tracking_date' => NULL,
                'stop_tracking_date' => NULL,
                'instructions' => NULL,
                'deleted_at' => NULL,
                'image_url' => NULL,
                'user_variable_id' => '31',
                'latest_tracking_reminder_notification_notify_at' => '2022-10-02 20:00:00',
                'number_of_tracking_reminder_notifications' => NULL,
            ),
        ));
        
        
    }
}
