<?php
namespace App\Folders;
namespace Tests\UnitTests\Folders;
use App\Computers\ThisComputer;
use App\Folders\DynamicFolder;
use App\Utils\AppMode;
use Tests\UnitTestCase;
/**
 * @package Tests\UnitTests\Files
 * @coversDefaultClass \App\Folders\DynamicFolder;
 */
class DynamicFolderTest extends UnitTestCase {
	/**
	 * @covers       DynamicFolder::dotsRelativeToRoot
	 * @noinspection PhpUnitMissingTargetForTestInspection (from a trait)
	 */
	public function testNumberOfDirectoriesToRelativeDotPathDynamicFolder(){
		$abs = abs_path();
		//$this->assertEquals("/www/wwwroot/qm-api/storage/framework", abs_path("storage/framework"));
		$num = DynamicFolder::numberOfDirsFromRoot("storage/framework/env_functions.sh");
		$this->assertEquals(3, $num);
		$dots = DynamicFolder::dotsRelativeToRoot("storage/framework/env_functions.sh");
		if(!AppMode::isWindows()){
			$cmd = ThisComputer::exec("cd ".abs_path("storage/framework")." && cd $dots && echo \$PWD");
			$this->assertEquals(abs_path(), $cmd);
			$this->assertEquals('../..', $dots);
		}
	}
	public function testGenerateConstants(){
		$this->skipTest("Get different results on slaves");
		$this->assertArrayEquals([
			'FOLDER_API' => 'Api',
			'FOLDER_APP' => 'app',
			'FOLDER_APP_ACTIONS' => 'app/Actions',
			'FOLDER_APP_ANALYTICS' => 'app/Analytics',
			'FOLDER_APP_APP_SETTINGS' => 'app/AppSettings',
			'FOLDER_APP_BUTTONS' => 'app/Buttons',
			'FOLDER_APP_CARDS' => 'app/Cards',
			'FOLDER_APP_CHARTS' => 'app/Charts',
			'FOLDER_APP_CODE_GENERATORS' => 'app/CodeGenerators',
			'FOLDER_APP_CONSOLE' => 'app/Console',
			'FOLDER_APP_CONVERSATIONS' => 'app/Conversations',
			'FOLDER_APP_CORRELATIONS' => 'app/VariableRelationships',
			'FOLDER_APP_DATA_SOURCES' => 'app/DataSources',
			'FOLDER_APP_DATA_TABLE_SERVICES' => 'app/DataTableServices',
			'FOLDER_APP_DEV_OPS' => 'app/DevOps',
			'FOLDER_APP_EVENTS' => 'app/Events',
			'FOLDER_APP_EXCEPTIONS' => 'app/Exceptions',
			'FOLDER_APP_FILES' => 'app/Files',
			'FOLDER_APP_FOLDERS' => 'app/Folders',
			'FOLDER_APP_FORMS' => 'app/Forms',
			'FOLDER_APP_FORMULAS' => 'app/Formulas',
			'FOLDER_APP_HELPERS' => 'app/Helpers',
			'FOLDER_APP_HTTP' => 'app/Http',
			'FOLDER_APP_IMPORTERS' => 'app/Importers',
			'FOLDER_APP_IMPORTS' => 'app/Imports',
			'FOLDER_APP_INPUT_FIELDS' => 'app/InputFields',
			'FOLDER_APP_INTENTS' => 'app/Intents',
			'FOLDER_APP_JOBS' => 'app/Jobs',
			'FOLDER_APP_LINKS' => 'app/Links',
			'FOLDER_APP_LISTENERS' => 'app/Listeners',
			'FOLDER_APP_LOGGING' => 'app/Logging',
			'FOLDER_APP_MAIL' => 'app/Mail',
			'FOLDER_APP_MENUS' => 'app/Menus',
			'FOLDER_APP_MODELS' => 'app/Models',
			'FOLDER_APP_NOTIFICATIONS' => 'app/Notifications',
			'FOLDER_APP_NOVA' => 'app/Astral',
			'FOLDER_APP_OBSERVERS' => 'app/Observers',
			'FOLDER_APP_OVERRIDE' => 'app/Override',
			'FOLDER_APP_PAGES' => 'app/Pages',
			'FOLDER_APP_PARAMETERS' => 'app/Parameters',
			'FOLDER_APP_POLICIES' => 'app/Policies',
			'FOLDER_APP_PRODUCTS' => 'app/Products',
			'FOLDER_APP_PROPERTIES' => 'app/Properties',
			'FOLDER_APP_PROVIDERS' => 'app/Providers',
			'FOLDER_APP_QUANTIMODO' => 'app/Quantimodo',
			'FOLDER_APP_REPORTS' => 'app/Reports',
			'FOLDER_APP_REPOS' => 'app/Repos',
			'FOLDER_APP_RULES' => 'app/Rules',
			'FOLDER_APP_SCRAPERS' => 'app/Scrapers',
			'FOLDER_APP_SCRIPTS' => 'app/Scripts',
			'FOLDER_APP_SERVICES' => 'app/Services',
			'FOLDER_APP_SHELL_COMMANDS' => 'app/ShellCommands',
			'FOLDER_APP_SOLUTIONS' => 'app/Solutions',
			'FOLDER_APP_SOLUTION_PROVIDERS' => 'app/SolutionProviders',
			'FOLDER_APP_SORTS' => 'app/Sorts',
			'FOLDER_APP_STORAGE' => 'app/Storage',
			'FOLDER_APP_STRATEGIES' => 'app/Strategies',
			'FOLDER_APP_STUDIES' => 'app/Studies',
			'FOLDER_APP_TABLES' => 'app/Tables',
			'FOLDER_APP_TRAITS' => 'app/Traits',
			'FOLDER_APP_TYPES' => 'app/Types',
			'FOLDER_APP_UI' => 'app/UI',
			'FOLDER_APP_UNITS' => 'app/Units',
			'FOLDER_APP_UNIT_CATEGORIES' => 'app/UnitCategories',
			'FOLDER_APP_UTILS' => 'app/Utils',
			'FOLDER_APP_VARIABLES' => 'app/Variables',
			'FOLDER_APP_VARIABLE_CATEGORIES' => 'app/VariableCategories',
			'FOLDER_APP_WIDGETS' => 'app/Widgets',
			'FOLDER_BIN' => 'bin',
			'FOLDER_BOOTSTRAP' => 'bootstrap',
			'FOLDER_BUILD' => 'build',
			'FOLDER_CONFIG' => 'config',
			'FOLDER_CONFIGS' => 'configs',
			'FOLDER_CONFIGS_AUTH' => 'configs/auth',
			'FOLDER_CONFIGS_ENVS' => 'configs/envs',
			'FOLDER_CONFIGS_ETC_DEV' => 'configs/etc-dev',
			'FOLDER_CONFIGS_ETC_GLOBAL' => 'configs/etc-global',
			'FOLDER_CONFIGS_GOOGLE' => 'configs/google',
			'FOLDER_CONFIGS_GOOGLE_PROGRAMMABLE_SEARCH' => 'configs/google-programmable-search',
			'FOLDER_CONFIGS_HOMESTEAD' => 'configs/homestead',
			'FOLDER_CONFIGS_HOME_DEV' => 'configs/home-dev',
			'FOLDER_CONFIGS_HOME_GLOBAL' => 'configs/home-global',
			'FOLDER_CONFIGS_HOME_WEB' => 'configs/home-web',
			'FOLDER_CONFIGS_IOS' => 'configs/ios',
			'FOLDER_CONFIGS_LARAGON' => 'configs/laragon',
			'FOLDER_CONFIGS_PHPSTORM' => 'configs/phpstorm',
			'FOLDER_CONFIGS_SSH_KEYS' => 'configs/ssh-keys',
			'FOLDER_CONFIGS_USR' => 'configs/usr',
			'FOLDER_CONFIGS_WINDOWS' => 'configs/windows',
			'FOLDER_CONFIGS_WP' => 'configs/wp',
			'FOLDER_CONFIGS_WSL' => 'configs/wsl',
			'FOLDER_CONFIGS_XHGUI' => 'configs/xhgui',
			'FOLDER_DATA' => 'data',
			'FOLDER_DATABASE' => 'database',
			'FOLDER_DATABASE_EXCEL' => 'database/excel',
			'FOLDER_DATABASE_FACTORIES' => 'database/factories',
			'FOLDER_DATABASE_MEDRA' => 'database/medra',
			'FOLDER_DATABASE_MIGRATIONS' => 'database/migrations',
			'FOLDER_DATABASE_SCRIPTS' => 'database/scripts',
			'FOLDER_DATABASE_SEEDS' => 'database/seeds',
			'FOLDER_DATABASE_TABLES' => 'database/tables',
			'FOLDER_DATABASE_TRIGGERS' => 'database/triggers',
			'FOLDER_DATABASE_VIEWS' => 'database/views',
			'FOLDER_DISCOVERY' => '.discovery',
			'FOLDER_DOCS' => 'docs',
			'FOLDER_GIT' => '.git',
			'FOLDER_GITHUB' => '.github',
			'FOLDER_JOBS' => 'Jobs',
			'FOLDER_LOG' => 'log',
			'FOLDER_NODE_MODULES' => 'node_modules',
			'FOLDER_NOVA' => 'astral',
			'FOLDER_PUBLIC' => 'public',
			'FOLDER_PUBLIC_ALPINE' => 'public/alpine',
			'FOLDER_PUBLIC_API' => 'public/api',
			'FOLDER_PUBLIC_APP_DESIGNER' => 'public/app-designer',
			'FOLDER_PUBLIC_BILLING' => 'public/billing',
			'FOLDER_PUBLIC_BUILDER' => 'public/builder',
			'FOLDER_PUBLIC_CSS' => 'public/css',
			'FOLDER_PUBLIC_DELETE' => 'public/delete',
			'FOLDER_PUBLIC_DEV' => 'public/dev',
			'FOLDER_PUBLIC_DEVELOPER' => 'public/developer',
			'FOLDER_PUBLIC_DEVELOPERS' => 'public/developers',
			'FOLDER_PUBLIC_DEV_DOCS' => 'public/dev-docs',
			'FOLDER_PUBLIC_DISCOVERIES' => 'public/discoveries',
			'FOLDER_PUBLIC_DOCS' => 'public/docs',
			'FOLDER_PUBLIC_DR' => 'public/dr',
			'FOLDER_PUBLIC_EMBEDDABLE' => 'public/embeddable',
			'FOLDER_PUBLIC_ERROR' => 'public/error',
			'FOLDER_PUBLIC_EXPORT' => 'public/export',
			'FOLDER_PUBLIC_FONTS' => 'public/fonts',
			'FOLDER_PUBLIC_GOACCESS' => 'public/goaccess',
			'FOLDER_PUBLIC_HOME' => 'public/home',
			'FOLDER_PUBLIC_IMG' => 'public/img',
			'FOLDER_PUBLIC_IMPORT' => 'public/import',
			'FOLDER_PUBLIC_IONIC' => 'public/ionic',
			'FOLDER_PUBLIC_JS' => 'public/js',
			'FOLDER_PUBLIC_LOGIN' => 'public/login',
			'FOLDER_PUBLIC_LOGOUT' => 'public/logout',
			'FOLDER_PUBLIC_MATERIAL' => 'public/material',
			'FOLDER_PUBLIC_PIMP' => 'public/pimp',
			'FOLDER_PUBLIC_PRIVACY' => 'public/privacy',
			'FOLDER_PUBLIC_PRIVACY_POLICY' => 'public/privacy-policy',
			'FOLDER_PUBLIC_QM_APPLICATION_SETTINGS' => 'public/qm-application-settings',
			'FOLDER_PUBLIC_QM_CONNECT' => 'public/qm-connect',
			'FOLDER_PUBLIC_QM_STATIC_DATA' => 'public/qm-static-data',
			'FOLDER_PUBLIC_REGISTER' => 'public/register',
			'FOLDER_PUBLIC_RESEARCHER' => 'public/researcher',
			'FOLDER_PUBLIC_RESEARCHERS' => 'public/researchers',
			'FOLDER_PUBLIC_STUDY' => 'public/study',
			'FOLDER_PUBLIC_SVG' => 'public/svg',
			'FOLDER_PUBLIC_TAILWIND' => 'public/tailwind',
			'FOLDER_PUBLIC_UPGRADE' => 'public/upgrade',
			'FOLDER_PUBLIC_UPLOADS' => 'public/uploads',
			'FOLDER_PUBLIC_VENDOR' => 'public/vendor',
			'FOLDER_PUBLIC_VENDORS' => 'public/vendors',
			'FOLDER_PUBLIC_WP' => 'public/wp',
			'FOLDER_REPOS' => 'repos',
			'FOLDER_RESOURCES' => 'resources',
			'FOLDER_RESOURCES_ASSETS' => 'resources/assets',
			'FOLDER_RESOURCES_JS' => 'resources/js',
			'FOLDER_RESOURCES_JSON_RESPONSES' => 'resources/json-responses',
			'FOLDER_RESOURCES_LANG' => 'resources/lang',
			'FOLDER_RESOURCES_LARAVEL_CODE_GENERATOR' => 'resources/laravel-code-generator',
			'FOLDER_RESOURCES_MODEL_SCHEMAS' => 'resources/model_schemas',
			'FOLDER_RESOURCES_SASS' => 'resources/sass',
			'FOLDER_RESOURCES_TEMPLATES' => 'resources/templates',
			'FOLDER_RESOURCES_VIEWS' => 'resources/views',
			'FOLDER_ROUTES' => 'routes',
			'FOLDER_RUN' => '.run',
			'FOLDER_SCRIPTS' => 'scripts',
			'FOLDER_SCRIPTS_DEPLOY' => 'scripts/deploy',
			'FOLDER_SCRIPTS_FILES' => 'scripts/files',
			'FOLDER_SCRIPTS_GIT' => 'scripts/git',
			'FOLDER_SCRIPTS_LIB' => 'storage/framework',
			'FOLDER_SCRIPTS_MONGO' => 'scripts/mongo',
			'FOLDER_SCRIPTS_MYSQL' => 'scripts/mysql',
			'FOLDER_SCRIPTS_PHP' => 'scripts/php',
			'FOLDER_SCRIPTS_PROVISION' => 'scripts/provision',
			'FOLDER_SCRIPTS_TESTS' => 'scripts/tests',
			'FOLDER_SCRIPTS_WSL' => 'scripts/wsl',
			'FOLDER_STATIC' => 'static',
			'FOLDER_STORAGE' => 'storage',
			'FOLDER_TESTS' => 'tests',
			'FOLDER_TESTS_AP_IS' => 'tests/APIs',
			'FOLDER_TESTS_BROWSER' => 'tests/Browser',
			'FOLDER_TESTS_SLIM_TESTS' => 'tests/SlimTests',
			'FOLDER_TESTS_DUSK' => 'tests/Dusk',
			'FOLDER_TESTS_FIXTURES' => 'tests/fixtures',
			'FOLDER_TESTS_GENERATED' => 'tests/Generated',
			'FOLDER_TESTS_IVR' => 'tests/IVR',
			'FOLDER_TESTS_LARAVEL_TESTS' => 'tests/LaravelTests',
			'FOLDER_TESTS_PHPSTORM_REQUESTS' => 'tests/phpstorm requests',
			'FOLDER_TESTS_STAGING_UNIT_TESTS' => 'tests/StagingUnitTests',
			'FOLDER_TESTS_TEST_GENERATORS' => 'tests/TestGenerators',
			'FOLDER_TESTS_TRAITS' => 'tests/Traits',
			'FOLDER_TESTS_UNIT_TESTS' => 'tests/UnitTests',
			'FOLDER_TMP' => 'tmp',
			'FOLDER_VENDOR' => 'vendor',
			'FOLDER_VENDOR_OVERRIDES' => 'vendor-overrides',], DynamicFolder::outputConstants());
	}
}
