<?php
/*
*  GNU General Public License v3.0
*  Contributors: ADD YOUR NAME HERE, Mike P. Sinn
 */

namespace App\VariableCategories;
use App\Properties\VariableCategory\VariableCategoryValenceProperty;
use App\UI\ImageUrls;
use App\Properties\VariableCategory\VariableCategoryFillingTypeProperty;
use App\Units\OneToFiveRatingUnit;
use App\Properties\VariableCategory\VariableCategoryCombinationOperationProperty;
use App\UI\FontAwesome;
use App\Variables\QMVariableCategory;
class EmotionsVariableCategory extends QMVariableCategory {
	public const WP_POST_ID = null;
	public const UPDATED_AT = '2021-02-06 19:32:42';
	public const SORT_ORDER = 0;
	public const NUMBER_OF_VARIABLES = 2028;
	public const NUMBER_OF_USER_VARIABLES = 43085;
	public const NUMBER_OF_PREDICTOR_POPULATION_STUDIES = 41770;
	public const NUMBER_OF_PREDICTOR_CASE_STUDIES = 101580;
	public const NUMBER_OF_OUTCOME_POPULATION_STUDIES = 5394;
	public const NUMBER_OF_OUTCOME_CASE_STUDIES = 17690;
	public const NUMBER_OF_MEASUREMENTS = 1211325;
	public const NAME_SINGULAR = 'Emotion';
	public const MEDIAN_SECONDS_BETWEEN_MEASUREMENTS = null;
	public const IS_PUBLIC = true;
	public const IS_GOAL = true;
	public const DELETED_AT = null;
	public const CREATED_AT = '2020-07-28 17:56:03';
	public const CONTROLLABLE = false;
	public const AVERAGE_SECONDS_BETWEEN_MEASUREMENTS = null;
	public const AMAZON_PRODUCT_CATEGORY = null;
	public const APP_TYPE = 'mood';
	public const BORING = false;
	public const CAUSE_ONLY = false;
	public const COMBINATION_OPERATION = VariableCategoryCombinationOperationProperty::COMBINATION_MEAN;
	public const COMMON = true;
	public const DEFAULT_UNIT_ABBREVIATED_NAME = '/5';
	public const DEFAULT_UNIT_ID = OneToFiveRatingUnit::ID;
	public const DURATION_OF_ACTION = 86400;
	public const EFFECT_ONLY = null;
	public const FILLING_TYPE = VariableCategoryFillingTypeProperty::FILLING_TYPE_NONE;
	public const FILLING_VALUE = -1;
	public const HELP_TEXT = 'What emotion do you want to rate?';
	public const FONT_AWESOME = FontAwesome::GRIN_TONGUE_WINK;
	public const ID = 1;
	public const IMAGE_URL = ImageUrls::THEATRE_MASK_96_PNG;
	public const ION_ICON = 'ion-happy-outline';
	public const MANUAL_TRACKING = true;
	public const MAXIMUM_ALLOWED_VALUE = null;
	public const MEASUREMENT_SYNONYM_SINGULAR_LOWERCASE = 'rating';
	public const MINIMUM_ALLOWED_SECONDS_BETWEEN_MEASUREMENTS = 60;
	public const MINIMUM_ALLOWED_VALUE = null;
	public const MORE_INFO = 'Do you have any emotions that fluctuate regularly?  If so, add them so I can try to determine which factors are influencing them.';
	public const NAME = 'Emotions';
	public const ONSET_DELAY = 0;
	public const OUTCOME = true;
	public const PNG_PATH = 'img/variable_categories/emotions.png';
    public const PNG_URL = 'https://static.quantimo.do/img/variable_categories/emotions.png';
	public const PREDICTOR = false;
	public const PUBLIC = true;
	public const SETUP_QUESTION = 'What is an unpleasant emotion like guiltiness, irritability, or nervousness you experience regularly?';
	public const STUDY_IMAGE_FILE_NAME = null;
	public const SUFFIX = null;
	public const SVG_PATH = 'img/variable_categories/emotions.svg';
    public const SVG_URL = 'https://static.quantimo.do/img/variable_categories/emotions.svg';
	public const SYNONYMS = ['Emotions', 'Emotion', 'Mood'];
	public const VALENCE = VariableCategoryValenceProperty::VALENCE_NEUTRAL;
	public const VARIABLE_CATEGORY_NAME = 'Emotions';
	public const VARIABLE_CATEGORY_NAME_SINGULAR = 'Emotion';
    public $amazonProductCategory = self::AMAZON_PRODUCT_CATEGORY;
	public $appType = self::APP_TYPE;
	public $boring = self::BORING;
	public $causeOnly = self::CAUSE_ONLY;
	public $combinationOperation = self::COMBINATION_OPERATION;
	public $common = self::COMMON;
	public $defaultUnitAbbreviatedName = self::DEFAULT_UNIT_ABBREVIATED_NAME;
	public $defaultUnitId = self::DEFAULT_UNIT_ID;
	public $durationOfAction = self::DURATION_OF_ACTION;
	public $effectOnly = self::EFFECT_ONLY;
	public $fillingType = self::FILLING_TYPE;
	public ?float $fillingValue = self::FILLING_VALUE;
	public $helpText = self::HELP_TEXT;
	public $fontAwesome = self::FONT_AWESOME;
	public $id = self::ID;
	public $imageUrl = self::IMAGE_URL;
	public $ionIcon = self::ION_ICON;
	public $manualTracking = self::MANUAL_TRACKING;
	public $maximumAllowedValue = self::MAXIMUM_ALLOWED_VALUE;
	public $measurementSynonymSingularLowercase = self::MEASUREMENT_SYNONYM_SINGULAR_LOWERCASE;
	public $minimumAllowedSecondsBetweenMeasurements = self::MINIMUM_ALLOWED_SECONDS_BETWEEN_MEASUREMENTS;
	public $minimumAllowedValue = self::MINIMUM_ALLOWED_VALUE;
	public $moreInfo = self::MORE_INFO;
	public $name = self::NAME;
	public $onsetDelay = self::ONSET_DELAY;
	public $outcome = self::OUTCOME;
	public $pngPath = self::PNG_PATH;
	public $pngUrl = self::PNG_URL;
	public $predictor = self::PREDICTOR;
	public $public = self::PUBLIC;
	public $setupQuestion = self::SETUP_QUESTION;
	public $studyImageFileName = self::STUDY_IMAGE_FILE_NAME;
	public $suffix = self::SUFFIX;
	public $svgPath = self::SVG_PATH;
	public $svgUrl = self::SVG_URL;
	public $synonyms = self::SYNONYMS;
	public $valence = self::VALENCE;
	public $variableCategoryName = self::VARIABLE_CATEGORY_NAME;
	public $variableCategoryNameSingular = self::VARIABLE_CATEGORY_NAME_SINGULAR;
}
