{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "WHOOP API"
  },
  "servers" : [ {
    "url" : "https://api.prod.whoop.com/developer"
  } ],
  "paths" : {
    "/v1/cycle/{cycleId}" : {
      "get" : {
        "tags" : [ "Cycle" ],
        "description" : "Get the cycle for the specified ID",
        "operationId" : "getCycleById",
        "security" : [ {
          "OAuth" : [ "read:cycles" ]
        } ]
      }
    },
    "/v1/cycle" : {
      "get" : {
        "tags" : [ "Cycle" ],
        "description" : "Get all physiological cycles for a user, paginated. Results are sorted by start time in descending order.",
        "operationId" : "getCycleCollection",
        "security" : [ {
          "OAuth" : [ "read:cycles" ]
        } ]
      }
    },
    "/v1/recovery" : {
      "get" : {
        "tags" : [ "Recovery" ],
        "description" : "Get all recoveries for a user, paginated. Results are sorted by start time of the related sleep in descending order.",
        "operationId" : "getRecoveryCollection",
        "security" : [ {
          "OAuth" : [ "read:recovery" ]
        } ]
      }
    },
    "/v1/cycle/{cycleId}/recovery" : {
      "get" : {
        "tags" : [ "Recovery" ],
        "description" : "Get the recovery for a cycle",
        "operationId" : "getRecoveryForCycle",
        "security" : [ {
          "OAuth" : [ "read:recovery" ]
        } ]
      }
    },
    "/v1/activity/sleep/{sleepId}" : {
      "get" : {
        "tags" : [ "Sleep" ],
        "description" : "Get the sleep for the specified ID",
        "operationId" : "getSleepById",
        "security" : [ {
          "OAuth" : [ "read:sleep" ]
        } ]
      }
    },
    "/v1/activity/sleep" : {
      "get" : {
        "tags" : [ "Sleep" ],
        "description" : "Get all sleeps for a user, paginated. Results are sorted by start time in descending order.",
        "operationId" : "getSleepCollection",
        "security" : [ {
          "OAuth" : [ "read:sleep" ]
        } ]
      }
    },
    "/v1/user/measurement/body" : {
      "get" : {
        "tags" : [ "User" ],
        "description" : "Get the user's body measurements",
        "operationId" : "getBodyMeasurement",
        "security" : [ {
          "OAuth" : [ "read:body_measurement" ]
        } ]
      }
    },
    "/v1/user/profile/basic" : {
      "get" : {
        "tags" : [ "User" ],
        "description" : "Get the user's Basic Profile",
        "operationId" : "getProfileBasic",
        "security" : [ {
          "OAuth" : [ "read:profile" ]
        } ]
      }
    },
    "/v1/activity/workout/{workoutId}" : {
      "get" : {
        "tags" : [ "Workout" ],
        "description" : "Get the workout for the specified ID",
        "operationId" : "getWorkoutById",
        "security" : [ {
          "OAuth" : [ "read:workout" ]
        } ]
      }
    },
    "/v1/activity/workout" : {
      "get" : {
        "tags" : [ "Workout" ],
        "description" : "Get all workouts for a user, paginated. Results are sorted by start time in descending order.",
        "operationId" : "getWorkoutCollection",
        "security" : [ {
          "OAuth" : [ "read:workout" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "OAuth" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://api.prod.whoop.com/oauth/oauth2/auth",
            "tokenUrl" : "https://api.prod.whoop.com/oauth/oauth2/token",
            "scopes" : {
              "read:recovery" : "Read Recovery data, including score, heart rate variability, and resting heart rate.",
              "read:cycles" : "Read cycles data, including day Strain and average heart rate during a physiological cycle.",
              "read:workout" : "Read workout data, including activity Strain and average heart rate.",
              "read:sleep" : "Read sleep data, including performance % and duration per sleep stage.",
              "read:profile" : "Read profile data, including name and email.",
              "read:body_measurement" : "Read body measurements data, including height, weight, and max heart rate."
            }
          }
        }
      }
    }
  }
}
