let GOOGLE_CLIENT_ID = process.env.CONNECTOR_GOOGLE_CLIENT_ID || "REDACTED_GOOGLE_CLIENT_SECRET";
let GOOGLE_CLIENT_SECRET = process.env.CONNECTOR_GOOGLE_CLIENT_SECRET || "REDACTED_GOOGLE_CLIENT_ID";
const QUANTIMODO_CLIENT_ID = process.env.CONNECTOR_QUANTIMODO_CLIENT_ID || 'oauth_test_client';
const QUANTIMODO_CLIENT_SECRET = process.env.CONNECTOR_QUANTIMODO_CLIENT_SECRET || 'REDACTED_QUANTIMODO_CLIENT_SECRET';
module.exports = {
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    QUANTIMODO_CLIENT_ID,
    QUANTIMODO_CLIENT_SECRET
}
