/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nt6swWQ68T5
 */
import Link from "next/link"
import { UserMenu } from './UserMenu';
import { User } from 'next-auth';

export function Navbar({user}: {user?: User}) {

  return (
    <header className="flex items-center h-14 px-4 border-b gap-4 lg:px-6">
      <Link className="flex items-center gap-2" href="#">
        <PackageIcon className="w-6 h-6" />
        <span className="font-semibold">FDAi Next.js Example</span>
      </Link>
      <nav className="flex flex-1 items-center justify-center space-x-4 lg:space-x-4">
        <Link className="font-medium underline hover:no-underline" href="#">
          Pricing
        </Link>
        <Link className="font-medium underline hover:no-underline" href="#">
          Features
        </Link>
        <Link className="font-medium underline hover:no-underline" href="#">
          Contact
        </Link>
        <Link className="font-medium underline hover:no-underline" href="#">
          About
        </Link>
        <Link className="font-medium underline hover:no-underline" href="#">
          Blog
        </Link>
        <Link className="font-medium underline hover:no-underline" href="#">
          Resources
        </Link>
        <Link className="font-medium underline hover:no-underline" href="#">
          Docs
        </Link>
      </nav>
      {user && <UserMenu user={user} />}
    </header>
  )
}


function PackageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m7.5 4.27 9 5.15" />
      <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  )
}


