<ul>
    <li>Activities Icons made by <a title="Darius Dan" href="http://www.flaticon.com/authors/darius-dan">Darius Dan</a> from <a title="Flaticon" href="http://www.flaticon.com/">www.flaticon.com</a></li>
    <li>Agriculture Published by <a title="Roundicons" href="http://www.flaticon.com/authors/roundicons">Roundicons</a> from <a title="Flaticon" href="http://www.flaticon.com/">www.flaticon.com</a></li>
    <li><a title="Pixel Buddha" href="http://www.flaticon.com/authors/pixel-buddha">Pixel Buddha</a> Pack: <a title="Basic Flat Icons" href="http://www.flaticon.com/packs/basic-flat-icons">Basic Flat Icons</a> from <a title="Flaticon" href="http://www.flaticon.com/">www.flaticon.com</a></li>
    <li><a title="Madebyoliver" href="http://www.flaticon.com/authors/madebyoliver">Madebyoliver</a> Pack: <a title="Business Collection" href="http://www.flaticon.com/packs/business-collection-3">Business Collection</a> from <a title="Flaticon" href="http://www.flaticon.com/">www.flaticon.com</a></li>
    <li><a title="Flat Icons" href="http://www.flaticon.com/authors/flat-icons">Flat Icons</a> Pack: <a title="Business Strategy" href="http://www.flaticon.com/packs/business-strategy">Business Strategy</a> from <a title="Flaticon" href="http://www.flaticon.com/">www.flaticon.com</a></li>
    <li><a title="Freepik" href="http://www.flaticon.com/authors/freepik">Freepik</a> Pack: <a title="Medical Elements" href="http://www.flaticon.com/packs/medical-elements">Medical Elements</a> from <a title="Flaticon" href="http://www.flaticon.com/">www.flaticon.com</a></li>
    <li><a title="Madebyoliver" href="http://www.flaticon.com/authors/madebyoliver">Madebyoliver</a> Pack: <a title="Emoticon Set" href="http://www.flaticon.com/packs/emoticon-set">Emoticon Set</a> from <a title="Flaticon" href="http://www.flaticon.com/">www.flaticon.com</a></li>
    <li><a title="Freepik" href="http://www.flaticon.com/authors/freepik">Freepik</a> Pack: <a title="Education elements" href="http://www.flaticon.com/packs/education-elements-3">Education Elements</a> from <a title="Flaticon" href="http://www.flaticon.com/">www.flaticon.com</a></li>
    <li><a title="Freepik" href="http://www.flaticon.com/authors/freepik">Freepik</a> Pack: <a title="Work productivity" href="http://www.flaticon.com/packs/work-productivity-9">Work Productivity</a> from <a title="Flaticon" href="http://www.flaticon.com/">www.flaticon.com</a></li>
</ul>