/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Quantimodo) {
      root.Quantimodo = {};
    }
    root.Quantimodo.TrackingReminderNotificationAction = factory(root.Quantimodo.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TrackingReminderNotificationAction model module.
   * @module model/TrackingReminderNotificationAction
   * @version 5.8.112511
   */

  /**
   * Constructs a new <code>TrackingReminderNotificationAction</code>.
   * @alias module:model/TrackingReminderNotificationAction
   * @class
   * @param action {String} Ex: track
   * @param callback {String} Ex: trackThreeRatingAction
   * @param modifiedValue {Number} Ex: 3
   * @param title {String} Ex: 3/5
   */
  var exports = function(action, callback, modifiedValue, title) {
    var _this = this;

    _this['action'] = action;
    _this['callback'] = callback;
    _this['modifiedValue'] = modifiedValue;
    _this['title'] = title;


  };

  /**
   * Constructs a <code>TrackingReminderNotificationAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackingReminderNotificationAction} obj Optional instance to populate.
   * @return {module:model/TrackingReminderNotificationAction} The populated <code>TrackingReminderNotificationAction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('action')) {
        obj['action'] = ApiClient.convertToType(data['action'], 'String');
      }
      if (data.hasOwnProperty('callback')) {
        obj['callback'] = ApiClient.convertToType(data['callback'], 'String');
      }
      if (data.hasOwnProperty('modifiedValue')) {
        obj['modifiedValue'] = ApiClient.convertToType(data['modifiedValue'], 'Number');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('longTitle')) {
        obj['longTitle'] = ApiClient.convertToType(data['longTitle'], 'String');
      }
      if (data.hasOwnProperty('shortTitle')) {
        obj['shortTitle'] = ApiClient.convertToType(data['shortTitle'], 'String');
      }
    }
    return obj;
  }

  /**
   * Ex: track
   * @member {String} action
   */
  exports.prototype['action'] = undefined;
  /**
   * Ex: trackThreeRatingAction
   * @member {String} callback
   */
  exports.prototype['callback'] = undefined;
  /**
   * Ex: 3
   * @member {Number} modifiedValue
   */
  exports.prototype['modifiedValue'] = undefined;
  /**
   * Ex: 3/5
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * Ex: Rate 3/5
   * @member {String} longTitle
   */
  exports.prototype['longTitle'] = undefined;
  /**
   * Ex: 3
   * @member {String} shortTitle
   */
  exports.prototype['shortTitle'] = undefined;



  return exports;
}));


