/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Quantimodo) {
      root.Quantimodo = {};
    }
    root.Quantimodo.XprofileField = factory(root.Quantimodo.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The XprofileField model module.
   * @module model/XprofileField
   * @version 5.8.112511
   */

  /**
   * Constructs a new <code>XprofileField</code>.
   * @alias module:model/XprofileField
   * @class
   * @param id {Number} What do you expect?
   * @param groupId {Number} What do you expect?
   * @param parentId {Number} What do you expect?
   * @param type {String} What do you expect?
   * @param name {String} What do you expect?
   * @param description {String} What do you expect?
   * @param isRequired {Number} What do you expect?
   * @param isDefaultOption {Number} What do you expect?
   * @param fieldOrder {Number} What do you expect?
   * @param optionOrder {Number} What do you expect?
   * @param orderBy {String} What do you expect?
   * @param canDelete {Number} What do you expect?
   */
  var exports = function(id, groupId, parentId, type, name, description, isRequired, isDefaultOption, fieldOrder, optionOrder, orderBy, canDelete) {
    var _this = this;

    _this['id'] = id;
    _this['groupId'] = groupId;
    _this['parentId'] = parentId;
    _this['type'] = type;
    _this['name'] = name;
    _this['description'] = description;
    _this['isRequired'] = isRequired;
    _this['isDefaultOption'] = isDefaultOption;
    _this['fieldOrder'] = fieldOrder;
    _this['optionOrder'] = optionOrder;
    _this['orderBy'] = orderBy;
    _this['canDelete'] = canDelete;

  };

  /**
   * Constructs a <code>XprofileField</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/XprofileField} obj Optional instance to populate.
   * @return {module:model/XprofileField} The populated <code>XprofileField</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('groupId')) {
        obj['groupId'] = ApiClient.convertToType(data['groupId'], 'Number');
      }
      if (data.hasOwnProperty('parentId')) {
        obj['parentId'] = ApiClient.convertToType(data['parentId'], 'Number');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('isRequired')) {
        obj['isRequired'] = ApiClient.convertToType(data['isRequired'], 'Number');
      }
      if (data.hasOwnProperty('isDefaultOption')) {
        obj['isDefaultOption'] = ApiClient.convertToType(data['isDefaultOption'], 'Number');
      }
      if (data.hasOwnProperty('fieldOrder')) {
        obj['fieldOrder'] = ApiClient.convertToType(data['fieldOrder'], 'Number');
      }
      if (data.hasOwnProperty('optionOrder')) {
        obj['optionOrder'] = ApiClient.convertToType(data['optionOrder'], 'Number');
      }
      if (data.hasOwnProperty('orderBy')) {
        obj['orderBy'] = ApiClient.convertToType(data['orderBy'], 'String');
      }
      if (data.hasOwnProperty('canDelete')) {
        obj['canDelete'] = ApiClient.convertToType(data['canDelete'], 'Number');
      }
      if (data.hasOwnProperty('metaDataArray')) {
        obj['metaDataArray'] = ApiClient.convertToType(data['metaDataArray'], [Object]);
      }
    }
    return obj;
  }

  /**
   * What do you expect?
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * What do you expect?
   * @member {Number} groupId
   */
  exports.prototype['groupId'] = undefined;
  /**
   * What do you expect?
   * @member {Number} parentId
   */
  exports.prototype['parentId'] = undefined;
  /**
   * What do you expect?
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * What do you expect?
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * What do you expect?
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * What do you expect?
   * @member {Number} isRequired
   */
  exports.prototype['isRequired'] = undefined;
  /**
   * What do you expect?
   * @member {Number} isDefaultOption
   */
  exports.prototype['isDefaultOption'] = undefined;
  /**
   * What do you expect?
   * @member {Number} fieldOrder
   */
  exports.prototype['fieldOrder'] = undefined;
  /**
   * What do you expect?
   * @member {Number} optionOrder
   */
  exports.prototype['optionOrder'] = undefined;
  /**
   * What do you expect?
   * @member {String} orderBy
   */
  exports.prototype['orderBy'] = undefined;
  /**
   * What do you expect?
   * @member {Number} canDelete
   */
  exports.prototype['canDelete'] = undefined;
  /**
   * Additional xprofilefield key-value data
   * @member {Array.<Object>} metaDataArray
   */
  exports.prototype['metaDataArray'] = undefined;



  return exports;
}));


