/**
 * Decentralized FDA API
 * A platform for quantifying the effects of every drug, supplement, food, and other factor on your health.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class Chart {
    /**
    *  Highcharts config that can be used if you have highcharts.js included on the page
    */
    'highchartConfig'?: any;
    /**
    * Ex: correlationScatterPlot
    */
    'chartId'?: string;
    /**
    * Ex: Overall Mood following Sleep Duration (R = -0.173)
    */
    'chartTitle'?: string;
    /**
    * Ex: The chart above indicates that an increase in Sleep Duration is usually followed by a decrease in Overall Mood.
    */
    'explanation'?: string;
    /**
    * Url to a static svg of the chart
    */
    'svgUrl'?: string;
    /**
    * SVG string than can be embedded directly in HTML
    */
    'svg'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "highchartConfig",
            "baseName": "highchartConfig",
            "type": "any",
            "format": ""
        },
        {
            "name": "chartId",
            "baseName": "chartId",
            "type": "string",
            "format": ""
        },
        {
            "name": "chartTitle",
            "baseName": "chartTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "explanation",
            "baseName": "explanation",
            "type": "string",
            "format": ""
        },
        {
            "name": "svgUrl",
            "baseName": "svgUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "svg",
            "baseName": "svg",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Chart.attributeTypeMap;
    }

    public constructor() {
    }
}

