/**
 * Decentralized FDA API
 * A platform for quantifying the effects of every drug, supplement, food, and other factor on your health.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class DeviceToken {
    /**
    * Client id
    */
    'clientId'?: string;
    /**
    * ios, android, or web
    */
    'platform': string;
    /**
    * The device token
    */
    'deviceToken': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "clientId",
            "baseName": "clientId",
            "type": "string",
            "format": ""
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "string",
            "format": ""
        },
        {
            "name": "deviceToken",
            "baseName": "deviceToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeviceToken.attributeTypeMap;
    }

    public constructor() {
    }
}

