/**
 * Decentralized FDA API
 * A platform for quantifying the effects of every drug, supplement, food, and other factor on your health.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Button } from '../models/Button';


export class ExplanationStartTracking {
    'button': Button;
    /**
    * Ex: The more data I have the more accurate your results will be so track regularly!
    */
    'description': string;
    /**
    * Ex: Improve Accuracy
    */
    'title': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "button",
            "baseName": "button",
            "type": "Button",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExplanationStartTracking.attributeTypeMap;
    }

    public constructor() {
    }
}

