/**
 * Decentralized FDA API
 * A platform for quantifying the effects of every drug, supplement, food, and other factor on your health.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export class VariableCategory {
    /**
    * Ex: mood
    */
    'appType'?: string;
    /**
    * Ex: false
    */
    'causeOnly'?: boolean;
    /**
    * Ex: MEAN
    */
    'combinationOperation'?: string;
    /**
    * UTC ISO 8601 YYYY-MM-DDThh:mm:ss
    */
    'createdTime'?: string;
    /**
    * Ex: /5
    */
    'unitAbbreviatedName'?: string;
    /**
    * Ex: 10
    */
    'unitId'?: number;
    /**
    * User-Defined Variable Setting: The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.  Unit: Seconds
    */
    'durationOfAction'?: number;
    /**
    * Ex: -1. Unit: Variable category default unit.
    */
    'fillingValue'?: number;
    /**
    * Ex: What emotion do you want to rate?
    */
    'helpText'?: string;
    /**
    * Ex: 1
    */
    'id'?: number;
    /**
    * Ex: https://static.quantimo.do/img/variable_categories/theatre_mask-96.png
    */
    'imageUrl'?: string;
    /**
    * Ex: ion-happy-outline
    */
    'ionIcon'?: string;
    /**
    * Ex: true
    */
    'manualTracking'?: boolean;
    /**
    * Unit: Variable category default unit.
    */
    'maximumAllowedValue'?: string;
    /**
    * Ex: rating
    */
    'measurementSynonymSingularLowercase'?: string;
    /**
    * Unit: Variable category default unit.
    */
    'minimumAllowedValue'?: string;
    /**
    * Ex: Do you have any emotions that fluctuate regularly?  If so, add them so I can try to determine which factors are influencing them.
    */
    'moreInfo'?: string;
    /**
    * Category name
    */
    'name': string;
    /**
    * Ex: 0
    */
    'onsetDelay'?: number;
    /**
    * Ex: true
    */
    'outcome'?: boolean;
    /**
    * Ex: img/variable_categories/emotions.png
    */
    'pngPath'?: string;
    /**
    * Ex: https://safe.dfda.earth/img/variable_categories/emotions.png
    */
    'pngUrl'?: string;
    /**
    * Ex: true
    */
    '_public'?: boolean;
    /**
    * Ex: img/variable_categories/emotions.svg
    */
    'svgPath'?: string;
    /**
    * Ex: https://safe.dfda.earth/img/variable_categories/emotions.svg
    */
    'svgUrl'?: string;
    /**
    * Ex: 1
    */
    'updated'?: number;
    /**
    * UTC ISO 8601 YYYY-MM-DDThh:mm:ss
    */
    'updatedTime'?: string;
    /**
    * Ex: Emotions, Treatments, Symptoms...
    */
    'variableCategoryName'?: VariableCategoryVariableCategoryNameEnum;
    /**
    * Ex: Emotion
    */
    'variableCategoryNameSingular'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appType",
            "baseName": "appType",
            "type": "string",
            "format": ""
        },
        {
            "name": "causeOnly",
            "baseName": "causeOnly",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "combinationOperation",
            "baseName": "combinationOperation",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdTime",
            "baseName": "createdTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "unitAbbreviatedName",
            "baseName": "unitAbbreviatedName",
            "type": "string",
            "format": ""
        },
        {
            "name": "unitId",
            "baseName": "unitId",
            "type": "number",
            "format": ""
        },
        {
            "name": "durationOfAction",
            "baseName": "durationOfAction",
            "type": "number",
            "format": ""
        },
        {
            "name": "fillingValue",
            "baseName": "fillingValue",
            "type": "number",
            "format": ""
        },
        {
            "name": "helpText",
            "baseName": "helpText",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "imageUrl",
            "baseName": "imageUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "ionIcon",
            "baseName": "ionIcon",
            "type": "string",
            "format": ""
        },
        {
            "name": "manualTracking",
            "baseName": "manualTracking",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "maximumAllowedValue",
            "baseName": "maximumAllowedValue",
            "type": "string",
            "format": ""
        },
        {
            "name": "measurementSynonymSingularLowercase",
            "baseName": "measurementSynonymSingularLowercase",
            "type": "string",
            "format": ""
        },
        {
            "name": "minimumAllowedValue",
            "baseName": "minimumAllowedValue",
            "type": "string",
            "format": ""
        },
        {
            "name": "moreInfo",
            "baseName": "moreInfo",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "onsetDelay",
            "baseName": "onsetDelay",
            "type": "number",
            "format": ""
        },
        {
            "name": "outcome",
            "baseName": "outcome",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "pngPath",
            "baseName": "pngPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "pngUrl",
            "baseName": "pngUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "_public",
            "baseName": "public",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "svgPath",
            "baseName": "svgPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "svgUrl",
            "baseName": "svgUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "number",
            "format": ""
        },
        {
            "name": "updatedTime",
            "baseName": "updatedTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "variableCategoryName",
            "baseName": "variableCategoryName",
            "type": "VariableCategoryVariableCategoryNameEnum",
            "format": ""
        },
        {
            "name": "variableCategoryNameSingular",
            "baseName": "variableCategoryNameSingular",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VariableCategory.attributeTypeMap;
    }

    public constructor() {
    }
}


export type VariableCategoryVariableCategoryNameEnum = "Activity" | "Books" | "Causes of Illness" | "Cognitive Performance" | "Conditions" | "Emotions" | "Environment" | "Foods" | "Goals" | "Locations" | "Miscellaneous" | "Movies and TV" | "Music" | "Nutrients" | "Payments" | "Physical Activities" | "Physique" | "Sleep" | "Social Interactions" | "Software" | "Symptoms" | "Treatments" | "Vital Signs" ;

