<?php namespace Tests\APIs;

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\UnitTestCase;
use Tests\ApiTestTrait;
use App\Models\SentEmail;

class SentEmailApiTest extends UnitTestCase
{
    use ApiTestTrait;
    public function setUp(): void
    {
        $this->markTestSkipped('Not implemented yet.');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_create_sent_email()
    {
        $sentEmail = SentEmail::factory()->make()->toArray();

        $r = $this->jsonAsUser18535(
            'POST',
            '/api/v6/sent_emails', $sentEmail
        );

        $this->assertApiResponse($sentEmail);
    }

    public function test_read_sent_email()
    {
        $sentEmail = SentEmail::fakeSaveFromPropertyModels();

        $r = $this->jsonAsUser18535(
            'GET',
            '/api/v6/sent_emails/'.$sentEmail->id
        );

        $this->assertApiResponse($sentEmail->toArray());
    }

    public function test_update_sent_email()
    {
        $sentEmail = SentEmail::fakeSaveFromPropertyModels();
        $editedSentEmail = SentEmail::factory()->make()->toArray();

        $r = $this->jsonAsUser18535(
            'PUT',
            '/api/v6/sent_emails/'.$sentEmail->id,
            $editedSentEmail
        );

        $this->assertApiResponse($editedSentEmail);
    }

    public function test_delete_sent_email()
    {
        $sentEmail = SentEmail::fakeSaveFromPropertyModels();

        $r = $this->jsonAsUser18535(
            'DELETE',
             '/api/v6/sent_emails/'.$sentEmail->id
         );

        $this->assertApiSuccess();
        $r = $this->jsonAsUser18535(
            'GET',
            '/api/v6/sent_emails/'.$sentEmail->id
        );

        $this->testResponse->assertStatus(404);
    }
}
