<?php namespace Tests\APIs;

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\UnitTestCase;
use Tests\ApiTestTrait;
use App\Models\TrackingReminderNotification;

class TrackingReminderNotificationApiTest extends UnitTestCase
{
    use ApiTestTrait;
    public function setUp(): void
    {
        $this->markTestSkipped('Not implemented yet.');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_create_tracking_reminder_notification()
    {
        $trackingReminderNotification = TrackingReminderNotification::factory()->make()->toArray();

        $r = $this->jsonAsUser18535(
            'POST',
            '/api/v6/tracking_reminder_notifications', $trackingReminderNotification
        );

        $this->assertApiResponse($trackingReminderNotification);
    }

    public function test_read_tracking_reminder_notification()
    {
        $trackingReminderNotification = TrackingReminderNotification::fakeSaveFromPropertyModels();

        $r = $this->jsonAsUser18535(
            'GET',
            '/api/v6/tracking_reminder_notifications/'.$trackingReminderNotification->id
        );

        $this->assertApiResponse($trackingReminderNotification->toArray());
    }

    public function test_update_tracking_reminder_notification()
    {
        $trackingReminderNotification = TrackingReminderNotification::fakeSaveFromPropertyModels();
        $editedTrackingReminderNotification = TrackingReminderNotification::factory()->make()->toArray();

        $r = $this->jsonAsUser18535(
            'PUT',
            '/api/v6/tracking_reminder_notifications/'.$trackingReminderNotification->id,
            $editedTrackingReminderNotification
        );

        $this->assertApiResponse($editedTrackingReminderNotification);
    }

    public function test_delete_tracking_reminder_notification()
    {
        $trackingReminderNotification = TrackingReminderNotification::fakeSaveFromPropertyModels();

        $r = $this->jsonAsUser18535(
            'DELETE',
             '/api/v6/tracking_reminder_notifications/'.$trackingReminderNotification->id
         );

        $this->assertApiSuccess();
        $r = $this->jsonAsUser18535(
            'GET',
            '/api/v6/tracking_reminder_notifications/'.$trackingReminderNotification->id
        );

        $this->testResponse->assertStatus(404);
    }
}
