<?php namespace Tests\APIs;

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\UnitTestCase;
use Tests\ApiTestTrait;
use App\Models\UserTag;

class UserTagApiTest extends UnitTestCase
{
    use ApiTestTrait;
    public function setUp(): void
    {
        $this->markTestSkipped('Not implemented yet.');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_create_user_tag()
    {
        $userTag = UserTag::factory()->make()->toArray();

        $r = $this->jsonAsUser18535(
            'POST',
            '/api/v6/user_tags', $userTag
        );

        $this->assertApiResponse($userTag);
    }

    public function test_read_user_tag()
    {
        $userTag = UserTag::fakeSaveFromPropertyModels();

        $r = $this->jsonAsUser18535(
            'GET',
            '/api/v6/user_tags/'.$userTag->id
        );

        $this->assertApiResponse($userTag->toArray());
    }

    public function test_update_user_tag()
    {
        $userTag = UserTag::fakeSaveFromPropertyModels();
        $editedUserTag = UserTag::factory()->make()->toArray();

        $r = $this->jsonAsUser18535(
            'PUT',
            '/api/v6/user_tags/'.$userTag->id,
            $editedUserTag
        );

        $this->assertApiResponse($editedUserTag);
    }

    public function test_delete_user_tag()
    {
        $userTag = UserTag::fakeSaveFromPropertyModels();

        $r = $this->jsonAsUser18535(
            'DELETE',
             '/api/v6/user_tags/'.$userTag->id
         );

        $this->assertApiSuccess();
        $r = $this->jsonAsUser18535(
            'GET',
            '/api/v6/user_tags/'.$userTag->id
        );

        $this->testResponse->assertStatus(404);
    }
}
