<?php
/*
*  GNU General Public License v3.0
*  Contributors: ADD YOUR NAME HERE, Mike P. Sinn
 */
namespace App\Properties\Variable;
use App\Models\User;
use App\Models\Variable;
use App\Properties\User\UserIdProperty;
use App\Traits\PropertyTraits\VariableProperty;
use App\Properties\Base\BaseCreatorUserIdProperty;
use Database\Seeders\DatabaseSeeder;
class VariableCreatorUserIdProperty extends BaseCreatorUserIdProperty
{
    use VariableProperty;
    public $table = Variable::TABLE;
    public $parentClass = Variable::class;
    public $name = Variable::FIELD_CREATOR_USER_ID;
    public $required = true;
    public $example = UserIdProperty::USER_ID_SYSTEM;
    public static function fromRequest(bool $throwException = false)
    {
        return parent::fromRequest($throwException); // TODO: Change the autogenerated stub
    }
    public function validate(): void
    {
        if(DatabaseSeeder::isReprocessingSeed()){
            $system = User::system();
            $this->setValue($system->getId());
            return;
        }
        parent::validate();
    }
}
