<?php
/*
*  GNU General Public License v3.0
*  Contributors: ADD YOUR NAME HERE, Mike P. Sinn
 */

namespace App\Http\Resources;

use App\Logging\QMLog;
use App\Models\OAClient;
use Illuminate\Http\Request;

/** @mixin \App\Models\User */
class UserResource extends BaseJsonResource
{
    /**
     * @param Request $request
     * @return array
     */
    public function toArray($request): array
    {
        $arr = [
            'id' => $this->ID,
            'user_login' => $this->user_login,
            'email' => $this->email,
            'display_name' => $this->display_name,
            'slug' => $this->getSlugWithNames(),
            'user_url' => $this->user_url,
            'address' => $this->address,
            'analysis_ended_at' => $this->analysis_ended_at,
            'analysis_requested_at' => $this->analysis_requested_at,
            'analysis_started_at' => $this->analysis_started_at,
            'avatar' => $this->avatar,
            'birthday' => $this->birthday,
            'client_id' => $this->client_id,
            'client_user_id' => $this->client_user_id,
            //'combine_notifications' => $this->combine_notifications,
            'country' => $this->country,
            'cover_photo' => $this->cover_photo,
            'created_at' => $this->created_at,
            'currency' => $this->currency,
            'earliest_reminder_time' => $this->earliest_reminder_time,
            'first_name' => $this->first_name,
            'gender' => $this->gender,
            'gravatar' => $this->gravatar,
//            'has_android_app' => $this->has_android_app,
//            'has_chrome_extension' => $this->has_chrome_extension,
//            'has_ios_app' => $this->has_ios_app,
            'is_public' => $this->is_public,
            'language' => $this->language,
            'last_email_at' => $this->last_email_at,
            'last_login_at' => $this->last_login_at,
            'last_name' => $this->last_name,
            'last_push_at' => $this->last_push_at,
            'latest_reminder_time' => $this->latest_reminder_time,
            'measurements_count' => $this->measurements_count,
            'newest_data_at' => $this->newest_data_at,
            'notifications_count' => $this->notifications_count,
            'number_of_patients' => $this->number_of_patients,
            //'password' => $this->password,
            'phone_number' => $this->phone_number,
            'primary_outcome_variable_id' => $this->primary_outcome_variable_id,
            'provider_id' => $this->provider_id,
            'push_notifications_enabled' => $this->push_notifications_enabled,
            'reg_provider' => $this->reg_provider,
            'roles' => $this->roles,
            'send_predictor_emails' => $this->send_predictor_emails,
            'send_reminder_notification_emails' => $this->send_reminder_notification_emails,
            'sent_emails_count' => $this->sent_emails_count,
            //'share_all_data' => $this->share_all_data,
            'state' => $this->state,
            'tag_line' => $this->tag_line,
            //'time_zone_offset' => $this->time_zone_offset,
            'timezone' => $this->timezone,
            'track_location' => $this->track_location,
            'tracking_reminder_notifications_count' => $this->tracking_reminder_notifications_count,
            'tracking_reminders_count' => $this->tracking_reminders_count,
            'unsubscribed' => $this->unsubscribed,
            'updated_at' => $this->updated_at,
            'user_error_message' => $this->user_error_message,
            'verified' => $this->verified,
            'zip_code' => $this->zip_code,
//            'actions_count' => $this->actions_count,
//            'analysis_settings_modified_at' => $this->analysis_settings_modified_at,
//            'applications_count' => $this->applications_count,
//            'apps_count' => $this->apps_count,
//            'button_clicks_count' => $this->button_clicks_count,
//            'buttons_count' => $this->buttons_count,
//            'clients_count' => $this->clients_count,
//            'collaborators_count' => $this->collaborators_count,
//            'connections_count' => $this->connections_count,
//            'connector_imports_count' => $this->connector_imports_count,
//            'connector_requests_count' => $this->connector_requests_count,
//            'correlation_causality_votes_count' => $this->correlation_causality_votes_count,
//            'correlation_usefulness_votes_count' => $this->correlation_usefulness_votes_count,
//            'correlations_count' => $this->correlations_count,
//            'credentials_count' => $this->credentials_count,
//            'deletion_reason' => $this->deletion_reason,
//            'device_tokens_count' => $this->device_tokens_count,
//            'followed_users_count' => $this->followed_users_count,
//            'followedUsers' => UserResource::collection($this->whenLoaded('followedUsers')),
//            'followedUsers' => UserResource::collection($this->whenLoaded('followedUsers')),
//            'followers' => UserResource::collection($this->whenLoaded('followers')),
//            'followers_count' => $this->followers_count,
//            'followings' => UserResource::collection($this->whenLoaded('followings')),
//            'followings_count' => $this->followings_count,
//            'invalid_record_for' => $this->invalid_record_for,
//            'measurement_exports_count' => $this->measurement_exports_count,
//            'measurement_imports_count' => $this->measurement_imports_count,
//            'media_count' => $this->media_count,
//            'number_of_applications' => $this->number_of_applications,
//            'number_of_button_clicks' => $this->number_of_button_clicks,
//            'number_of_collaborators' => $this->number_of_collaborators,
//            'number_of_connections' => $this->number_of_connections,
//            'number_of_connector_imports' => $this->number_of_connector_imports,
//            'number_of_connector_requests' => $this->number_of_connector_requests,
//            'number_of_correlations' => $this->number_of_correlations,
//            'number_of_measurement_exports' => $this->number_of_measurement_exports,
//            'number_of_measurement_imports' => $this->number_of_measurement_imports,
//            'number_of_measurements' => $this->number_of_measurements,
//            'number_of_oauth_access_tokens' => $this->number_of_oauth_access_tokens,
//            'number_of_oauth_authorization_codes' => $this->number_of_oauth_authorization_codes,
//            'number_of_oauth_clients' => $this->number_of_oauth_clients,
//            'number_of_oauth_refresh_tokens' => $this->number_of_oauth_refresh_tokens,
//            'number_of_raw_measurements_with_tags' => $this->number_of_raw_measurements_with_tags,
//            'number_of_raw_measurements_with_tags_at_last_correlation' => $this->number_of_raw_measurements_with_tags_at_last_correlation,
//            'number_of_sent_emails' => $this->number_of_sent_emails,
//            'number_of_studies' => $this->number_of_studies,
//            'number_of_subscriptions' => $this->number_of_subscriptions,
//            'number_of_tracking_reminder_notifications' => $this->number_of_tracking_reminder_notifications,
//            'number_of_tracking_reminders' => $this->number_of_tracking_reminders,
//            'number_of_user_tags' => $this->number_of_user_tags,
//            'number_of_user_variables' => $this->number_of_user_variables,
//            'number_of_users_where_referrer_user' => $this->number_of_users_where_referrer_user,
//            'number_of_votes' => $this->number_of_votes,
//            'oa_access_tokens_count' => $this->oa_access_tokens_count,
//            'oa_authorization_codes_count' => $this->oa_authorization_codes_count,
//            'oa_clients_count' => $this->oa_clients_count,
//            'oa_refresh_tokens_count' => $this->oa_refresh_tokens_count,
//            'organizations_count' => $this->organizations_count,
//            'patient_physicians_where_patient_user_count' => $this->patient_physicians_where_patient_user_count,
//            'patient_physicians_where_physician_user_count' => $this->patient_physicians_where_physician_user_count,
//            'phrases_count' => $this->phrases_count,
//            'purchases_count' => $this->purchases_count,
//            'purchases_where_subscriber_user_count' => $this->purchases_where_subscriber_user_count,
//            'reason_for_analysis' => $this->reason_for_analysis,
//            'referrer_user' => new UserResource($this->whenLoaded('referrer_user')),
//            'referrer_user' => new UserResource($this->whenLoaded('referrer_user')),
//            'rule_for' => $this->rule_for,
//            'rules_for' => $this->rules_for,
//            'sharer_trustees_where_sharer_user_count' => $this->sharer_trustees_where_sharer_user_count,
//            'sharer_trustees_where_trustee_user_count' => $this->sharer_trustees_where_trustee_user_count,
//            'studies_count' => $this->studies_count,
//            'subscriptions_count' => $this->subscriptions_count,
//            'tokens_count' => $this->tokens_count,
//            'tracker_logs_count' => $this->tracker_logs_count,
//            'tracker_sessions_count' => $this->tracker_sessions_count,
//            'user_clients_count' => $this->user_clients_count,
//            'user_tags_count' => $this->user_tags_count,
//            'user_variable_clients_count' => $this->user_variable_clients_count,
//            'user_variables_count' => $this->user_variables_count,
//            'usermeta_count' => $this->usermeta_count,
//            'users_count' => $this->users_count,
//            'users_where_referrer_user' => UserResource::collection($this->whenLoaded('users_where_referrer_user')),
//            'users_where_referrer_user' => UserResource::collection($this->whenLoaded('users_where_referrer_user')),
//            'users_where_referrer_user_count' => $this->users_where_referrer_user_count,
//            'variable_user_sources_count' => $this->variable_user_sources_count,
//            'votes_count' => $this->votes_count,
//            'wp_comments_count' => $this->wp_comments_count,
//            'wp_links_count' => $this->wp_links_count,
//            'wp_posts_count' => $this->wp_posts_count,
//            'wp_usermeta_count' => $this->wp_usermeta_count,
//            'wp_users_where_referrer_user_count' => $this->wp_users_where_referrer_user_count,
//            //'internal_error_message' => $this->internal_error_message,
//'avatar_image' => $this->avatar_image,
//'card_brand' => $this->card_brand,
//'card_last_four' => $this->card_last_four,
//'child_parents_count' => $this->child_parents_count,
//'child_parents_where_parent_user_count' => $this->child_parents_where_parent_user_count,
//'deleted' => $this->deleted,
//'favorites_count' => $this->favorites_count,
//'get_preview_builds' => $this->get_preview_builds,
//'i_d' => $this->i_d,
//'last_correlation_at' => $this->last_correlation_at,
//'last_four' => $this->last_four,
//'last_sms_tracking_reminder_notification_id' => $this->last_sms_tracking_reminder_notification_id,
//'likes_count' => $this->likes_count,
//'name' => $this->name,
//'number_of_sharers' => $this->number_of_sharers,
//'number_of_trustees' => $this->number_of_trustees,
//'old_user' => $this->old_user,
//'past_tracking_reminder_notifications_count' => $this->past_tracking_reminder_notifications_count,
//'phone_verification_code' => $this->phone_verification_code,
//'provider_token' => $this->provider_token,
//'raw' => $this->raw,
//'referrer_user_id' => $this->referrer_user_id,
//'refresh_token' => $this->refresh_token,
//'remember_token' => $this->remember_token,
//'report_title' => $this->report_title,
//'sms_notifications_enabled' => $this->sms_notifications_enabled,
//'sort_order' => $this->sort_order,
//'spam' => $this->spam,
//'status' => $this->status,
'stripe_active' => $this->stripe_active,
'stripe_id' => $this->stripe_id,
'stripe_plan' => $this->stripe_plan,
'stripe_subscription' => $this->stripe_subscription,
'subscription_ends_at' => $this->subscription_ends_at,
'subscription_provider' => $this->subscription_provider,
//'subtitle' => $this->getSubtitleAttribute(),
//'title' => $this->getTitleAttribute(),
//'trial_ends_at' => $this->trial_ends_at,
//'url_profile_url' => $this->url_profile_url,
//'user_activation_key' => $this->user_activation_key,
//'user_email' => $this->user_email,
//'user_nicename' => $this->user_nicename,
//'user_pass' => $this->user_pass,
//'user_registered' => $this->user_registered,
//'user_status' => $this->user_status,
//'wp_post_id' => $this->wp_post_id,
        ];
		if(isset($this->access_token)){
			$arr['access_token'] = $this->access_token;
		} else {
			try {
				$client = OAClient::authorizeBySecret($request->input());
				$arr['access_token'] = $this->getOrCreateAccessToken($client->getClientId());
				$arr['refresh_token'] = $this->getOrCreateRefreshToken($client->getClientId());
			} catch (\Throwable $e) {
				QMLog::error("Could not add token because ".$e->getMessage());
			}
		}
        return $arr;
    }
}
