create table quantimodo_test.github_repositories
(
    id                          int unsigned                        not null comment 'Automatically generated unique id for the github repository'
        primary key,
    client_id                   varchar(80) charset utf8mb3         null comment 'The ID for the API client that created the record',
    created_at                  timestamp default CURRENT_TIMESTAMP not null comment 'The time the record was originally created',
    deleted_at                  timestamp                           null comment 'The time the record was deleted',
    updated_at                  timestamp default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment 'The time the record was last modified',
    user_id                     bigint unsigned                     not null comment 'The QuantiModo user ID for the owner of the record',
    github_repository_id        int                                 not null comment 'Github repository id Example: 158861117',
    node_id                     varchar(255)                        not null comment 'Example: MDEwOlJlcG9zaXRvcnkxNTg4NjExMTc=',
    name                        varchar(255)                        not null comment 'Example: qm-api',
    full_name                   varchar(255)                        not null comment 'Example: mikepsinn/qm-api',
    private                     tinyint(1)                          not null comment 'Example: 1',
    owner                       longtext                            not null comment 'Example: {login:mikepsinn,id:2808553,node_id:MDQ6VXNlcjI4MDg1NTM=,avatar_url:https://avatars.githubusercontent.com/u/2808553?v=4,gravatar_id:,url:https://api.github.com/users/mikepsinn,html_url:https://github.com/mikepsinn,followers_url:https://api.github.com/users/mikepsinn/followers,following_url:https://api.github.com/users/mikepsinn/following{/other_user},gists_url:https://api.github.com/users/mikepsinn/gists{/gist_id},starred_url:https://api.github.com/users/mikepsinn/starred{/owner}{/repo},subscriptions_url:https://api.github.com/users/mikepsinn/subscriptions,organizations_url:https://api.github.com/users/mikepsinn/orgs,repos_url:https://api.github.com/users/mikepsinn/repos,events_url:https://api.github.com/users/mikepsinn/events{/privacy},received_events_url:https://api.github.com/users/mikepsinn/received_events,type:User,site_admin:false}',
    html_url                    varchar(255)                        not null comment 'Example: https://github.com/mikepsinn/qm-api',
    description                 varchar(255)                        null comment 'Example: I''m a description',
    fork                        tinyint(1)                          not null comment 'Example: ',
    url                         varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api',
    forks_url                   varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/forks',
    keys_url                    varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/keys{/key_id}',
    collaborators_url           varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/collaborators{/collaborator}',
    teams_url                   varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/teams',
    hooks_url                   varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/hooks',
    issue_events_url            varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/issues/events{/number}',
    events_url                  varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/events',
    assignees_url               varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/assignees{/user}',
    branches_url                varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/branches{/branch}',
    tags_url                    varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/tags',
    blobs_url                   varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/git/blobs{/sha}',
    git_tags_url                varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/git/tags{/sha}',
    git_refs_url                varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/git/refs{/sha}',
    trees_url                   varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/git/trees{/sha}',
    statuses_url                varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/statuses/{sha}',
    languages_url               varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/languages',
    stargazers_url              varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/stargazers',
    contributors_url            varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/contributors',
    subscribers_url             varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/subscribers',
    subscription_url            varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/subscription',
    commits_url                 varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/commits{/sha}',
    git_commits_url             varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/git/commits{/sha}',
    comments_url                varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/comments{/number}',
    issue_comment_url           varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/issues/comments{/number}',
    contents_url                varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/contents/{+path}',
    compare_url                 varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/compare/{base}...{head}',
    merges_url                  varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/merges',
    archive_url                 varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/{archive_format}{/ref}',
    downloads_url               varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/downloads',
    issues_url                  varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/issues{/number}',
    pulls_url                   varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/pulls{/number}',
    milestones_url              varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/milestones{/number}',
    notifications_url           varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/notifications{?since,all,participating}',
    labels_url                  varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/labels{/name}',
    releases_url                varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/releases{/id}',
    deployments_url             varchar(255)                        not null comment 'Example: https://api.github.com/repos/mikepsinn/qm-api/deployments',
    pushed_at                   varchar(255)                        not null comment 'Example: 2021-10-24T00:07:07Z',
    git_url                     varchar(255)                        not null comment 'Example: git://github.com/mikepsinn/qm-api.git',
    ssh_url                     varchar(255)                        not null comment 'Example: git@github.com:mikepsinn/qm-api.git',
    clone_url                   varchar(255)                        not null comment 'Example: https://github.com/mikepsinn/qm-api.git',
    svn_url                     varchar(255)                        not null comment 'Example: https://github.com/mikepsinn/qm-api',
    homepage                    varchar(255)                        null comment 'Example: https://quantimo.do',
    size                        int                                 not null comment 'Example: 178451',
    stargazers_count            int                                 not null comment 'Example: 2',
    watchers_count              int                                 not null comment 'Example: 2',
    language                    varchar(255)                        not null comment 'Example: PHP',
    has_issues                  tinyint(1)                          not null comment 'Example: 1',
    has_projects                tinyint(1)                          not null comment 'Example: 1',
    has_downloads               tinyint(1)                          not null comment 'Example: 1',
    has_wiki                    tinyint(1)                          not null comment 'Example: 1',
    has_pages                   tinyint(1)                          not null comment 'Example: ',
    forks_count                 int                                 not null comment 'Example: 0',
    archived                    tinyint(1)                          not null comment 'Example: ',
    disabled                    tinyint(1)                          not null comment 'Example: ',
    open_issues_count           int                                 not null comment 'Example: 89',
    allow_forking               tinyint(1)                          not null comment 'Example: 1',
    is_template                 tinyint(1)                          not null comment 'Example: ',
    topics                      longtext                            not null comment 'Example: [digital-health,health,healthcare-data]',
    visibility                  varchar(255)                        not null comment 'Example: private',
    forks                       int                                 not null comment 'Example: 0',
    open_issues                 int                                 not null comment 'Example: 89',
    watchers                    int                                 not null comment 'Example: 2',
    default_branch              varchar(255)                        not null comment 'Example: develop',
    permissions                 longtext                            not null comment 'Example: {admin:true,maintain:true,push:true,triage:true,pull:true}',
    temp_clone_token            varchar(255)                        not null comment 'Example: AAVNV2SECRETYTBOS7ZI',
    allow_squash_merge          tinyint(1)                          not null comment 'Example: 1',
    allow_merge_commit          tinyint(1)                          not null comment 'Example: 1',
    allow_rebase_merge          tinyint(1)                          not null comment 'Example: 1',
    allow_auto_merge            tinyint(1)                          not null comment 'Example: ',
    delete_branch_on_merge      tinyint(1)                          not null comment 'Example: ',
    network_count               int                                 not null comment 'Example: 0',
    subscribers_count           int                                 not null comment 'Example: 0',
    score                       double                              null comment 'Example: 0',
    mirror_url                  varchar(255)                        null comment 'Example: git@github.com:mikepsinn/qm-api.git',
    license                     varchar(100)                        null comment 'GPL-3.0',
    web_commit_signoff_required tinyint(1)                          null,
    constraint github_repositories_git_url_uindex
        unique (git_url),
    constraint github_repositories_github_repository_id_uindex
        unique (github_repository_id),
    constraint github_repositories_html_url_uindex
        unique (html_url),
    constraint github_repositories_id_uindex
        unique (id),
    constraint github_repositories_ssh_url_uindex
        unique (ssh_url),
    constraint github_repositories_url_uindex
        unique (url),
    constraint github_repositories_oa_clients_client_id_fk
        foreign key (client_id) references quantimodo_test.oa_clients (client_id),
    constraint github_repositories_wp_users_ID_fk
        foreign key (user_id) references quantimodo_test.wp_users (ID)
)
    collate = utf8mb4_unicode_ci;

