openapi: 3.0.1
info:
  contact:
    name: Web API Support
    url: https://dev.fitbit.com/build/reference/web-api/help/
  description: 'Fitbit provides a Web API for accessing data from Fitbit activity
    trackers, Aria scale, and manually entered logs. Anyone can develop an application
    to access and modify a Fitbit user''s data on their behalf, so long as it complies
    with Fitbit Platform Terms of Service. These Swagger UI docs do not currently
    support making Fitbit API requests directly. In order to make a request, construct
    a request for the appropriate endpoint using this documentation, and then add
    an Authorization header to each request with an access token obtained using the
    steps outlined here: https://dev.fitbit.com/build/reference/web-api/oauth2/#obtaining-consent.'
  termsOfService: https://dev.fitbit.com/terms
  title: Fitbit Web API
  version: "1"
servers:
  - url: https://api.fitbit.com/
tags:
  - description: ""
    name: Activity
  - description: ""
    name: Activity Intraday Time Series
  - description: ""
    name: Activity Time Series
  - description: authentication and authorization using OAuth 2
    name: Auth
  - description: ""
    name: Body and Weight
  - description: ""
    name: Body and Weight Time Series
  - description: ""
    name: Breathing Rate
  - description: ""
    name: Breathing Rate Intraday
  - description: ""
    name: Cardio Fitness Score (VO2 Max)
  - description: ""
    name: Devices
  - description: ""
    name: Food and Water
  - description: ""
    name: Food and Water Time Series
  - description: ""
    name: Friends
  - description: ""
    name: Heart Rate Intraday Time Series
  - description: ""
    name: Heart Rate Time Series
  - description: ""
    name: Heart Rate Variability
  - description: ""
    name: Heart Rate Variability Intraday
  - description: ""
    name: Sleep
  - description: ""
    name: SpO2
  - description: ""
    name: SpO2 Intraday
  - description: ""
    name: Subscriptions
  - description: ""
    name: Temperature
  - description: ""
    name: User
paths:
  /oauth2/token:
    post:
      description: Retrieves an OAuth 2 access token.
      operationId: oauthToken
      summary: Get OAuth 2 access token
      tags:
        - Auth
  /1.1/oauth2/introspect:
    post:
      description: Retrieves the active state of an OAuth 2.0 token. It follows https://tools.ietf.org/html/rfc7662.
      operationId: introspect
      security:
        - oauth2: []
      summary: Retrieve the active state of an OAuth 2.0 token
      tags:
        - Auth
  /1/user/-/activities/date/{date}.json:
    get:
      description: Retrieves a summary and list of a user's activities and activity
        log entries for a given day.
      operationId: getActivitiesByDate
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: 'Get Activity Summary by Date '
      tags:
        - Activity
  /1/user/-/activities/{resource-path}/date/{base-date}/{end-date}.json:
    get:
      description: Returns activities time series data in the specified range for
        a given resource.
      operationId: getActivitiesResourceByDateRange
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Activity Resource by Date Range
      tags:
        - Activity Time Series
  /1/user/-/activities/tracker/{resource-path}/date/{base-date}/{end-date}.json:
    get:
      description: Returns time series data in the specified range for a given resource.
      operationId: getActivitiesTrackerResourceByDateRange
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Activity Tracker Resource by Date Range Time Series
      tags:
        - Activity Time Series
  /1/user/-/activities/{resource-path}/date/{date}/{period}.json:
    get:
      description: Returns time series data in the specified range for a given resource
        in the format requested using units in the unit system that corresponds to
        the Accept-Language header provided.
      operationId: getActivitiesResourceByDatePeriod
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Activity Time Series
      tags:
        - Activity Time Series
  /1/user/-/activities/tracker/{resource-path}/date/{date}/{period}.json:
    get:
      description: Returns time series data in the specified range for a given resource
        in the format requested using units in the unit system that corresponds to
        the Accept-Language header provided.
      operationId: getActivitiesTrackerResourceByDatePeriod
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Activity Time Series
      tags:
        - Activity Time Series
  /1/user/-/activities/{resource-path}/date/{base-date}/{end-date}/{detail-level}.json:
    get:
      description: Returns the Activity Intraday Time Series for a given resource
        in the format requested.
      operationId: getActivitiesResourceByDateRangeIntraday
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Activity Intraday Time Series
      tags:
        - Activity Intraday Time Series
  /1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}.json:
    get:
      description: Returns the Intraday Time Series for a given resource in the format
        requested.
      operationId: getActivitiesResourceByDateIntraday
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Intraday Time Series
      tags:
        - Activity Intraday Time Series
  /1/user/-/activities/{resource-path}/date/{date}/{end-date}/{detail-level}/time/{start-time}/{end-time}.json:
    get:
      description: Returns the Intraday Time Series for a given resource in the format
        requested.
      operationId: getActivitiesResourceByDateRangeTimeSeriesIntraday
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Activity Intraday Time Series
      tags:
        - Activity Intraday Time Series
  /1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json:
    get:
      description: Returns the Intraday Time Series for a given resource in the format
        requested.
      operationId: getActivitiesResourceByDateTimeSeriesIntraday
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Intraday Time Series
      tags:
        - Activity Intraday Time Series
  /1/user/-/activities.json:
    get:
      description: Updates a user's daily activity goals and returns a response using
        units in the unit system which corresponds to the Accept-Language header provided.
      operationId: getActivitiesLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Lifetime Stats
      tags:
        - Activity
    post:
      description: The Log Activity endpoint creates log entry for an activity or
        user's private custom activity using units in the unit system which corresponds
        to the Accept-Language header provided (or using optional custom distanceUnit)
        and get a response in the format requested.
      operationId: addActivitiesLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Log Activity
      tags:
        - Activity
  /1/user/-/activities/{activity-log-id}.json:
    delete:
      description: Deletes a user's activity log entry with the given ID.
      operationId: deleteActivitiesLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Delete Activity Log
      tags:
        - Activity
  /1/user/-/activities/list.json:
    get:
      description: Retreives a list of user's activity log entries before or after
        a given day with offset and limit using units in the unit system which corresponds
        to the Accept-Language header provided.
      operationId: getActivitiesLogList
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Activity Log List
      tags:
        - Activity
  /1/user/-/activities/{log-id}.tcx:
    get:
      description: Retreives the details of a user's location and heart rate data
        during a logged exercise activity.
      operationId: getActivitiesTCX
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Activity TCX
      tags:
        - Activity
  /1/activities.json:
    get:
      description: Retreives a tree of all valid Fitbit public activities from the
        activities catelog as well as private custom activities the user created in
        the format requested.
      operationId: getActivitiesTypes
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Browse Activity Types
      tags:
        - Activity
  /1/activities/{activity-id}.json:
    get:
      description: Returns the detail of a specific activity in the Fitbit activities
        database in the format requested. If activity has levels, it also returns
        a list of activity level details.
      operationId: getActivitiesTypeDetail
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Activity Type
      tags:
        - Activity
  /1/user/-/activities/frequent.json:
    get:
      description: Retreives a list of a user's frequent activities in the format
        requested using units in the unit system which corresponds to the Accept-Language
        header provided.
      operationId: getFrequentActivities
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Frequent Activities
      tags:
        - Activity
  /1/user/-/activities/recent.json:
    get:
      description: Retreives a list of a user's recent activities types logged with
        some details of the last activity log of that type using units in the unit
        system which corresponds to the Accept-Language header provided.
      operationId: getRecentActivities
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Recent Activity Types
      tags:
        - Activity
  /1/user/-/activities/favorite.json:
    get:
      description: Returns a list of a user's favorite activities.
      operationId: getFavoriteActivities
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Favorite Activities
      tags:
        - Activity
  /1/user/-/activities/favorite/{activity-id}.json:
    delete:
      description: Removes the activity with the given ID from a user's list of favorite
        activities.
      operationId: deleteFavoriteActivities
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Delete Favorite Activity
      tags:
        - Activity
    post:
      description: Adds the activity with the given ID to user's list of favorite
        activities.
      operationId: addFavoriteActivities
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Add Favorite Activity
      tags:
        - Activity
  /1/user/-/activities/goals/{period}.json:
    get:
      description: Retreives a user's current daily or weekly activity goals using
        measurement units as defined in the unit system, which corresponds to the
        Accept-Language header provided.
      operationId: getActivitiesGoals
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Activity Goals
      tags:
        - Activity
    post:
      description: Updates a user's daily or weekly activity goals and returns a response
        using units in the unit system which corresponds to the Accept-Language header
        provided.
      operationId: addUpdateActivitiesGoals
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Update Activity Goals
      tags:
        - Activity
  /1/user/-/body/log/fat/date/{date}.json:
    get:
      description: Retreives a list of all user's body fat log entries for a given
        day in the format requested.
      operationId: getBodyFatByDate
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Body Fat Logs
      tags:
        - Body and Weight
  /1/user/-/body/log/fat/date/{date}/{period}.json:
    get:
      description: Retreives a list of all user's body fat log entries for a given
        day in the format requested.
      operationId: getBodyFatByDatePeriod
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Body Fat Logs
      tags:
        - Body and Weight
  /1/user/-/body/log/fat/date/{base-date}/{end-date}.json:
    get:
      description: Retreives a list of all user's body fat log entries for a given
        day in the format requested.
      operationId: getBodyFatByDateRange
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Body Fat Logs
      tags:
        - Body and Weight
  /1/user/-/body/log/fat.json:
    post:
      description: Creates a log entry for body fat and returns a response in the
        format requested.
      operationId: addBodyFatLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Log Body Fat
      tags:
        - Body and Weight
  /1/user/-/body/log/fat/{body-fat-log-id}.json:
    delete:
      description: Deletes a user's body fat log entry with the given ID.
      operationId: deleteBodyFatLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Delete Body Fat Log
      tags:
        - Body and Weight
  /1/user/-/body/{resource-path}/date/{date}/{period}.json:
    get:
      description: Returns time series data in the specified range for a given resource
        in the format requested using units in the unit system that corresponds to
        the Accept-Language header provided.
      operationId: getBodyResourceByDatePeriod
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Body Time Series
      tags:
        - Body and Weight Time Series
  /1/user/-/body/{resource-path}/date/{base-date}/{end-date}.json:
    get:
      description: Returns time series data in the specified range for a given resource
        in the format requested using units in the unit system that corresponds to
        the Accept-Language header provided.
      operationId: getBodyResourceByDateRange
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Body Time Series
      tags:
        - Body and Weight Time Series
  /1/user/-/body/log/{goal-type}/goal.json:
    get:
      description: Retreives a user's current body fat percentage or weight goal using
        units in the unit systems that corresponds to the Accept-Language header providedin
        the format requested.
      operationId: getBodyGoals
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Body Goals
      tags:
        - Body and Weight
  /1/user/-/body/log/fat/goal.json:
    post:
      description: Updates user's fat percentage goal.
      operationId: UpdateBodyFatGoal
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Update Body Fat Goal
      tags:
        - Body and Weight
  /1/user/-/body/log/weight/goal.json:
    post:
      description: Updates user's fat percentage goal.
      operationId: updateWeightGoal
      security:
        - oauth2:
            - profile
            - heartrate
            - location
      summary: Update Weight Goal
      tags:
        - Body and Weight
  /1/user/-/body/log/weight/date/{date}.json:
    get:
      description: Retreives a list of all user's body weight log entries for a given
        day using units in the unit systems which corresponds to the Accept-Language
        header provided.
      operationId: getWeightByDate
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Weight Logs
      tags:
        - Body and Weight
  /1/user/-/body/log/weight/date/{date}/{period}.json:
    get:
      description: Retreives a list of all user's body weight log entries for a given
        day in the format requested.
      operationId: getWeightByDatePeriod
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Body Fat Logs
      tags:
        - Body and Weight
  /1/user/-/body/log/weight/date/{base-date}/{end-date}.json:
    get:
      description: Retreives a list of all user's body fat log entries for a given
        day in the format requested.
      operationId: getWeightByDateRange
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Body Fat Logs
      tags:
        - Body and Weight
  /1/user/-/body/log/weight.json:
    post:
      description: Creates log entry for a body weight using units in the unit systems
        that corresponds to the Accept-Language header provided and gets a response
        in the format requested.
      operationId: addWeightLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Log Weight
      tags:
        - Body and Weight
  /1/user/-/body/log/weight/{body-weight-log-id}.json:
    delete:
      description: Deletes a user's body weight log entrywith the given ID.
      operationId: deleteWeightLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Delete Weight Log
      tags:
        - Body and Weight
  /1/user/-/br/date/{date}.json:
    get:
      description: This endpoint returns average breathing rate data for a single
        date. Breathing Rate data applies specifically to a user’s “main sleep,” which
        is the longest single period of time during which they were asleep on a given
        date.
      operationId: getBreathingRateSummaryByDate
      security:
        - oauth2:
            - respiratory_rate
      summary: Get Breathing Rate Summary by Date
      tags:
        - Breathing Rate
  /1/user/-/br/date/{startDate}/{endDate}.json:
    get:
      description: This endpoint returns average breathing rate data for a date range.
        Breathing Rate data applies specifically to a user’s “main sleep,” which is
        the longest single period of time during which they were asleep on a given
        date.
      operationId: getBreathingRateSummaryByInterval
      security:
        - oauth2:
            - respiratory_rate
      summary: Get Breathing Rate Summary by Interval
      tags:
        - Breathing Rate
  /1/user/-/br/date/{date}/all.json:
    get:
      description: This endpoint returns intraday breathing rate data for a single
        date. It measures the average breathing rate throughout the day and categories
        your breathing rate by sleep stage. Sleep stages vary between light sleep,
        deep sleep, REM sleep, and full sleep.
      operationId: getBreathingRateIntradayByDate
      security:
        - oauth2:
            - respiratory_rate
      summary: Get Breathing Rate Intraday by Date
      tags:
        - Breathing Rate Intraday
  /1/user/-/br/date/{startDate}/{endDate}/all.json:
    get:
      description: This endpoint returns intraday breathing rate data for a date range.
        It measures the average breathing rate throughout the day and categories your
        breathing rate by sleep stage. Sleep stages vary between light sleep, deep
        sleep, REM sleep, and full sleep.
      operationId: getBreathingRateIntradayByInterval
      security:
        - oauth2:
            - respiratory_rate
      summary: Get Breathing Rate Intraday by Interval
      tags:
        - Breathing Rate Intraday
  /1/user/-/cardioscore/date/{date}.json:
    get:
      description: This endpoint returns the Cardio Fitness Score (VO2 Max) data for
        a single date. VO2 Max values will be shown as a range if no run data is available
        or a single numeric value if the user uses a GPS for runs.
      operationId: getVo2MaxSummaryByDate
      security:
        - oauth2:
            - cardio_fitness
      summary: Get VO2 Max Summary by Date
      tags:
        - Cardio Fitness Score (VO2 Max)
  /1/user/-/cardioscore/date/{startDate}/{endDate}.json:
    get:
      description: This endpoint returns the Cardio Fitness Score (VO2 Max) data for
        a date range. VO2 Max values will be shown as a range if no run data is available
        or a single numeric value if the user uses a GPS for runs.
      operationId: getVo2MaxSummaryByInterval
      security:
        - oauth2:
            - cardio_fitness
      summary: Get VO2 Max Summary by Interval
      tags:
        - Cardio Fitness Score (VO2 Max)
  /1/user/-/devices.json:
    get:
      description: Returns a list of the Fitbit devices connected to a user's account.
      operationId: getDevices
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Devices
      tags:
        - Devices
  /1/user/-/devices/tracker/{tracker-id}/alarms.json:
    get:
      description: Returns alarms for a device
      operationId: getAlarms
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Alarms
      tags:
        - Devices
    post:
      description: Adds the alarm settings to a given ID for a given device.
      operationId: addAlarms
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Add Alarm
      tags:
        - Devices
  /1/user/-/devices/tracker/{tracker-id}/alarms/{alarm-id}.json:
    delete:
      description: Deletes the user's device alarm entry with the given ID for a given
        device.
      operationId: deleteAlarms
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Delete Alarm
      tags:
        - Devices
    post:
      description: Updates the alarm entry with a given ID for a given device. It
        also gets a response in the format requested.
      operationId: updateAlarms
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Update Alarm
      tags:
        - Devices
  /1/foods/locales.json:
    get:
      description: Returns the food locales that the user may choose to search, log,
        and create food in.
      operationId: getFoodsLocales
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Food Locales
      tags:
        - Food and Water
  /1/user/-/foods/log/goal.json:
    get:
      description: Returns a user's current daily calorie consumption goal and/or
        foodPlan value in the format requested.
      operationId: getFoodsGoal
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Food Goals
      tags:
        - Food and Water
    post:
      description: Updates a user's daily calories consumption goal or food plan and
        returns a response in the format requested.
      operationId: addUpdateFoodsGoal
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Update Food Goal
      tags:
        - Food and Water
  /1/user/-/foods/log/date/{date}.json:
    get:
      description: Retreives a summary and list of a user's food log entries for a
        given day in the format requested.
      operationId: getFoodsByDate
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Food Logs
      tags:
        - Food and Water
  /1/user/-/foods/log/water/date/{date}.json:
    get:
      description: Retreives a summary and list of a user's water log entries for
        a given day in the requested using units in the unit system that corresponds
        to the Accept-Language header provided.
      operationId: getWaterByDate
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Water Logs
      tags:
        - Food and Water
  /1/user/-/foods/log/water/goal.json:
    get:
      description: Retreives a summary and list of a user's water goal entries for
        a given day in the requested using units in the unit system that corresponds
        to the Accept-Language header provided.
      operationId: getWaterGoal
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Water Goal
      tags:
        - Food and Water
    post:
      description: Updates a user's daily calories consumption goal or food plan and
        returns a response in the format requested.
      operationId: addUpdateWaterGoal
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Update Water Goal
      tags:
        - Food and Water
  /1/user/-/foods/log/{resource-path}/date/{base-date}/{end-date}.json:
    get:
      description: Updates a user's daily activity goals and returns a response using
        units in the unit system which corresponds to the Accept-Language header provided.
      operationId: getFoodsByDateRange
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Food or Water Time Series
      tags:
        - Food and Water Time Series
  /1/user/-/foods/log/{resource-path}/date/{date}/{period}.json:
    get:
      description: Updates a user's daily activity goals and returns a response using
        units in the unit system which corresponds to the Accept-Language header provided.
      operationId: getFoodsResourceByDatePeriod
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Food or Water Time Series
      tags:
        - Food and Water Time Series
  /1/user/-/foods/log.json:
    post:
      description: Creates food log entries for users with or without foodId value.
      operationId: addFoodsLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Log Food
      tags:
        - Food and Water
  /1/user/-/foods/log/{food-log-id}.json:
    delete:
      description: Deletes a user's food log entry with the given ID.
      operationId: deleteFoodsLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Delete Food Log
      tags:
        - Food and Water
    post:
      description: The Edit Food Log endpoint changes the quantity or calories consumed
        for a user's food log entry with the given Food Log ID.
      operationId: editFoodsLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Edit Food Log
      tags:
        - Food and Water
  /1/user/-/foods/log/water.json:
    post:
      description: Creates a log entry for water using units in the unit systems that
        corresponds to the Accept-Language header provided.
      operationId: addWaterLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Log Water
      tags:
        - Food and Water
  /1/user/-/foods/log/water/{water-log-id}.json:
    delete:
      description: Deletes a user's water log entry with the given ID.
      operationId: deleteWaterLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Delete Water Log
      tags:
        - Food and Water
    post:
      description: Updates a user's water log entry with the given ID.
      operationId: updateWaterLog
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Update Water Log
      tags:
        - Food and Water
  /1/user/-/foods/log/favorite.json:
    get:
      description: Returns a list of a user's favorite foods in the format requested.
        A favorite food in the list provides a quick way to log the food via the Log
        Food endpoint.
      operationId: getFavoriteFoods
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Favorite Foods
      tags:
        - Food and Water
  /1/user/-/foods/log/frequent.json:
    get:
      description: Returns a list of a user's frequent foods in the format requested.
        A frequent food in the list provides a quick way to log the food via the Log
        Food endpoint.
      operationId: getFrequentFoods
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Frequent Foods
      tags:
        - Food and Water
  /1/user/-/foods/log/favorite/{food-id}.json:
    delete:
      description: Deletes a food with the given ID to the user's list of favorite
        foods.
      operationId: deleteFavoriteFood
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Delete Favorite Food
      tags:
        - Food and Water
    post:
      description: Updates a user's daily activity goals and returns a response using
        units in the unit system which corresponds to the Accept-Language header provided.
      operationId: addFavoriteFood
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Add Favorite Food
      tags:
        - Food and Water
  /1/user/-/meals.json:
    get:
      description: Returns a list of meals created by user in the user's food log
        in the format requested. User creates and manages meals on the Food Log tab
        on the website.
      operationId: getMeals
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Meals
      tags:
        - Food and Water
    post:
      description: Creates a meal with the given food contained in the post body.
      operationId: addMeal
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Create Meal
      tags:
        - Food and Water
  /1/user/-/meals/{meal-id}.json:
    delete:
      description: Deletes a user's meal with the given meal id.
      operationId: deleteMeal
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Delete Meal
      tags:
        - Food and Water
    post:
      description: Replaces an existing meal with the contents of the request. The
        response contains the updated meal.
      operationId: updateMeal
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Edit Meal
      tags:
        - Food and Water
  /1/user/-/foods/log/recent.json:
    get:
      description: Returns a list of a user's frequent foods in the format requested.
        A frequent food in the list provides a quick way to log the food via the Log
        Food endpoint.
      operationId: getRecentFoods
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Recent Foods
      tags:
        - Food and Water
  /1/user/-/foods.json:
    post:
      description: Creates a new private food for a user and returns a response in
        the format requested. The created food is found via the Search Foods call.
      operationId: addFoods
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Create Food
      tags:
        - Food and Water
  /1/user/-/foods/{food-id}.json:
    delete:
      description: Deletes custom food for a user and returns a response in the format
        requested.
      operationId: deleteFoods
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Delete Custom Food
      tags:
        - Food and Water
  /1/foods/{food-id}.json:
    get:
      description: Returns the details of a specific food in the Fitbit food databases
        or a private food that an authorized user has entered in the format requested.
      operationId: getFoodsInfo
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Food
      tags:
        - Food and Water
  /1/foods/units.json:
    get:
      description: Returns a list of all valid Fitbit food units in the format requested.
      operationId: getFoodsUnits
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Food Units
      tags:
        - Food and Water
  /1/foods/search.json:
    get:
      description: Returns a list of public foods from the Fitbit food database and
        private food the user created in the format requested.
      operationId: getFoodsList
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Search Foods
      tags:
        - Food and Water
  /1.1/user/-/friends.json:
    get:
      description: Returns data of a user's friends in the format requested using
        units in the unit system which corresponds to the Accept-Language header provided.
      operationId: getFriends
      security:
        - oauth2:
            - social
      summary: Get Friends
      tags:
        - Friends
  /1.1/user/-/leaderboard/friends.json:
    get:
      description: Returns data of a user's friends in the format requested using
        units in the unit system which corresponds to the Accept-Language header provided.
      operationId: getFriendsLeaderboard
      security:
        - oauth2:
            - social
      summary: Get Friends Leaderboard
      tags:
        - Friends
  /1/user/-/activities/heart/date/{date}/{period}.json:
    get:
      description: Returns the time series data in the specified range for a given
        resource in the format requested using units in the unit systems that corresponds
        to the Accept-Language header provided.
      operationId: getHeartByDatePeriod
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Heart Rate Time Series
      tags:
        - Heart Rate Time Series
  /1/user/-/activities/heart/date/{base-date}/{end-date}.json:
    get:
      description: Returns the time series data in the specified range for a given
        resource in the format requested using units in the unit systems that corresponds
        to the Accept-Language header provided.
      operationId: getHeartByDateRange
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Heart Rate Time Series
      tags:
        - Heart Rate Time Series
  /1/user/-/activities/heart/date/{date}/{end-date}/{detail-level}.json:
    get:
      description: Returns the intraday time series for a given resource in the format
        requested. If your application has the appropriate access, your calls to a
        time series endpoint for a specific day (by using start and end dates on the
        same day or a period of 1d), the response will include extended intraday values
        with a one-minute detail level for that day. Unlike other time series calls
        that allow fetching data of other users, intraday data is available only for
        and to the authorized user.
      operationId: getHeartByDateRangeIntraday
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Heart Rate Intraday Time Series
      tags:
        - Heart Rate Intraday Time Series
  /1/user/-/activities/heart/date/{date}/{end-date}/{detail-level}/time/{start-time}/{end-time}.json:
    get:
      description: Returns the intraday time series for a given resource in the format
        requested. If your application has the appropriate access, your calls to a
        time series endpoint for a specific day (by using start and end dates on the
        same day or a period of 1d), the response will include extended intraday values
        with a one-minute detail level for that day. Unlike other time series calls
        that allow fetching data of other users, intraday data is available only for
        and to the authorized user.
      operationId: getHeartByDateRangeTimestampIntraday
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Heart Rate Intraday Time Series
      tags:
        - Heart Rate Intraday Time Series
  /1/user/-/activities/heart/date/{date}/1d/{detail-level}.json:
    get:
      description: Returns the intraday time series for a given resource in the format
        requested. If your application has the appropriate access, your calls to a
        time series endpoint for a specific day (by using start and end dates on the
        same day or a period of 1d), the response will include extended intraday values
        with a one-minute detail level for that day. Unlike other time series calls
        that allow fetching data of other users, intraday data is available only for
        and to the authorized user.
      operationId: getHeartByDateIntraday
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Heart Rate Intraday Time Series
      tags:
        - Heart Rate Intraday Time Series
  /1/user/-/activities/heart/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json:
    get:
      description: Returns the intraday time series for a given resource in the format
        requested. If your application has the appropriate access, your calls to a
        time series endpoint for a specific day (by using start and end dates on the
        same day or a period of 1d), the response will include extended intraday values
        with a one-minute detail level for that day. Unlike other time series calls
        that allow fetching data of other users, intraday data is available only for
        and to the authorized user.
      operationId: getHeartByDateTimestampIntraday
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Heart Rate Intraday Time Series
      tags:
        - Heart Rate Intraday Time Series
  /1/user/-/hrv/date/{date}.json:
    get:
      description: This endpoint returns the Heart Rate Variability (HRV) data for
        a single date. HRV data applies specifically to a user’s “main sleep,” which
        is the longest single period of time asleep on a given date.
      operationId: getHrvSummaryDate
      security:
        - oauth2:
            - heartrate
      summary: Get HRV Summary by Date
      tags:
        - Heart Rate Variability
  /1/user/-/hrv/date/{startDate}/{endDate}.json:
    get:
      description: This endpoint returns the Heart Rate Variability (HRV) data for
        a date range. HRV data applies specifically to a user’s “main sleep,” which
        is the longest single period of time asleep on a given date.
      operationId: getHrvSummaryInterval
      security:
        - oauth2:
            - heartrate
      summary: Get HRV Summary by Interval
      tags:
        - Heart Rate Variability
  /1/user/-/hrv/date/{date}/all.json:
    get:
      description: This endpoint returns the Heart Rate Variability (HRV) intraday
        data for a single date. HRV data applies specifically to a user’s “main sleep,”
        which is the longest single period of time asleep on a given date.
      operationId: getHrvIntradayByDate
      security:
        - oauth2:
            - heartrate
      summary: Get HRV Intraday by Date
      tags:
        - Heart Rate Variability Intraday
  /1/user/-/hrv/date/{startDate}/{endDate}/all.json:
    get:
      description: This endpoint returns the Heart Rate Variability (HRV) intraday
        data for a single date. HRV data applies specifically to a user’s “main sleep,”
        which is the longest single period of time asleep on a given date.
      operationId: getHrvIntradayByInterval
      security:
        - oauth2:
            - heartrate
      summary: Get HRV Intraday by Interval
      tags:
        - Heart Rate Variability Intraday
  /1.2/user/-/sleep/{log-id}.json:
    delete:
      description: Deletes a user's sleep log entry with the given ID.
      operationId: deleteSleep
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Delete Sleep Log
      tags:
        - Sleep
  /1.2/user/-/sleep/date/{date}.json:
    get:
      description: The Get Sleep Logs by Date endpoint returns a summary and list
        of a user's sleep log entries (including naps) as well as detailed sleep entry
        data for a given day.
      operationId: getSleepByDate
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Sleep Log
      tags:
        - Sleep
  /1.2/user/-/sleep/date/{base-date}/{end-date}.json:
    get:
      description: The Get Sleep Logs by Date Range endpoint returns a list of a user's
        sleep log entries (including naps) as well as detailed sleep entry data for
        a given date range (inclusive of start and end dates).
      operationId: getSleepByDateRange
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Sleep Logs by Date Range
      tags:
        - Sleep
  /1.2/user/-/sleep/list.json:
    get:
      description: The Get Sleep Logs List endpoint returns a list of a user's sleep
        logs (including naps) before or after a given day with offset, limit, and
        sort order.
      operationId: getSleepList
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Sleep Logs List
      tags:
        - Sleep
  /1.2/user/-/sleep/goal.json:
    get:
      description: Returns the user's sleep goal.
      operationId: getSleepGoal
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Sleep Goal
      tags:
        - Sleep
    post:
      description: Create or update the user's sleep goal and get a response in the
        JSON format.
      operationId: updateSleepGoal
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Update Sleep Goal
      tags:
        - Sleep
  /1.2/user/-/sleep.json:
    post:
      description: Creates a log entry for a sleep event and returns a response in
        the format requested.
      operationId: addSleep
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Log Sleep
      tags:
        - Sleep
  /1/user/-/spo2/date/{date}.json:
    get:
      description: This endpoint returns the SpO2 summary data for a single date.
        SpO2 applies specifically to a user’s “main sleep”, which is the longest single
        period of time asleep on a given date.
      operationId: getSpO2SummaryByDate
      security:
        - oauth2:
            - oxygen_saturation
      summary: Get SpO2 Summary by Date
      tags:
        - SpO2
  /1/user/-/spo2/date/{startDate}/{endDate}.json:
    get:
      description: This endpoint returns the SpO2 summary data for a date range. SpO2
        applies specifically to a user’s “main sleep”, which is the longest single
        period of time asleep on a given date.
      operationId: getSpO2SummaryByInterval
      security:
        - oauth2:
            - oxygen_saturation
      summary: Get SpO2 Summary by Interval
      tags:
        - SpO2
  /1/user/-/spo2/date/{date}/all.json:
    get:
      description: This endpoint returns the SpO2 intraday data for a single date.
        SpO2 applies specifically to a user’s “main sleep”, which is the longest single
        period of time asleep on a given date.
      operationId: getSpO2IntradayByDate
      security:
        - oauth2:
            - oxygen_saturation
      summary: Get SpO2 Intraday by Date
      tags:
        - SpO2 Intraday
  /1/user/-/spo2/date/{startDate}/{endDate}/all.json:
    get:
      description: This endpoint returns the SpO2 intraday data for a specified date
        range. SpO2 applies specifically to a user’s “main sleep”, which is the longest
        single period of time asleep on a given date.
      operationId: getSpO2IntradayByInterval
      security:
        - oauth2:
            - oxygen_saturation
      summary: Get SpO2 Intraday by Interval
      tags:
        - SpO2 Intraday
  /1/user/-/{collection-path}/apiSubscriptions.json:
    get:
      description: Retreives a list of a user's subscriptions for your application
        in the format requested. You can either fetch subscriptions for a specific
        collection or the entire list of subscriptions for the user. For best practice,
        make sure that your application maintains this list on your side and use this
        endpoint only to periodically ensure data consistency.
      operationId: getSubscriptionsList
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get a List of Subscriptions
      tags:
        - Subscriptions
  /1/user/-/{collection-path}/apiSubscriptions/{subscription-id}.json:
    delete:
      description: Deletes a subscription for a user..
      operationId: deleteSubscriptions
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Delete a Subscription
      tags:
        - Subscriptions
    post:
      description: Adds a subscription in your application so that users can get notifications
        and return a response in the format requested. The subscription-id value provides
        a way to associate an update with a particular user stream in your application.
      operationId: addSubscriptions
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Add a Subscription
      tags:
        - Subscriptions
  /1/user/-/temp/core/date/{date}.json:
    get:
      description: Returns the Temperature (Core) data for a single date. Temperature
        (Core) data applies specifically to data logged manually by the user throughout
        the day.
      operationId: getTempCoreSummaryByDate
      security:
        - oauth2:
            - temperature
      summary: Get Temperature (Core) Summary by Date
      tags:
        - Temperature
  /1/user/-/temp/core/date/{startDate}/{endDate}.json:
    get:
      description: Returns Temperature (Core) data for a date range. Temperature (Core)
        data applies specifically to data logged manually by the user throughout the
        day and the maximum date range cannot exceed 30 days.
      operationId: getTempCoreSummaryByInterval
      security:
        - oauth2:
            - temperature
      summary: Get Temperature (Core) Summary by Interval
      tags:
        - Temperature
  /1/user/-/temp/skin/date/{date}.json:
    get:
      description: Returns the Temperature (Skin) data for a single date. Temperature
        (Skin) data applies specifically to a user’s “main sleep”, which is the longest
        single period of time asleep on a given date.
      operationId: getTempSkinSummaryDate
      security:
        - oauth2:
            - temperature
      summary: Get Temperature (Skin) Summary by Date
      tags:
        - Temperature
  /1/user/-/temp/skin/date/{startDate}/{endDate}.json:
    get:
      description: Returns Temperature (Skin) data for a date range. It only returns
        a value for dates on which the Fitbit device was able to record Temperature
        (skin) data and the maximum date range cannot exceed 30 days.
      operationId: getTempSkinSummaryByInterval
      security:
        - oauth2:
            - temperature
      summary: Get Temperature (Skin) Summary by Interval
      tags:
        - Temperature
  /1/user/-/badges.json:
    get:
      description: Retrieves the user's badges in the format requested. Response includes
        all badges for the user as seen on the Fitbit website badge locker (both activity
        and weight related.) The endpoint returns weight and distance badges based
        on the user's unit profile preference as on the website.
      operationId: getBadges
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - weight
      summary: Get Badges
      tags:
        - User
  /1/user/-/profile.json:
    get:
      description: Returns a user's profile. The authenticated owner receives all
        values. However, the authenticated user's access to other users' data is subject
        to those users' privacy settings. Numerical values are returned in the unit
        system specified in the Accept-Language header.
      operationId: getProfile
      security:
        - oauth2:
            - location
            - profile
            - weight
      summary: Get Profile
      tags:
        - User
    post:
      description: Updates a user's profile using a form.
      operationId: updateProfile
      security:
        - oauth2:
            - activity
            - heartrate
            - location
            - nutrition
            - profile
            - settings
            - sleep
            - social
            - temperature
            - weight
      summary: Update Profile
      tags:
        - User
components:
  securitySchemes:
    oauth2:
      flows:
        implicit:
          authorizationUrl: https://www.fitbit.com/oauth2/authorize
          scopes:
            activity: Activity data and exercise log related features, such as steps,
              distance, calories burned, and active minutes
            cardio_fitness: Maximum or optimum rate at which the user’s heart, lungs,
              and muscles can effectively use oxygen during exercise
            heartrate: Continuous heart rate & HRV data and related analysis
            location: GPS and other location data
            nutrition: Calorie consumption and nutrition related features, such as
              food/water logging, goals, and plans
            oxygen_saturation: SpO2 (Oxygen Saturation) is a measurement of your blood
              oxygen level
            profile: Basic user information
            respiratory_rate: Respiratory Rate is a measurement of your breaths at
              night.
            settings: User account and device settings, such as alarms
            sleep: Sleep logs and related sleep analysis
            social: Friend-related features, such as friend list and leaderboard
            temperature: Core and skin temperature data
            weight: Weight and related information, such as body mass index, body
              fat percentage, and goals
      type: oauth2
x-original-swagger-version: "2.0"
